### ISSUE TITLE
Worlds Part 1 Update

### ISSUE THREAD

**Issue by goatfungus** [goatfungus/NMSSaveEditor#1019]
The new update for No Man's Sky, Worlds Part 1, introduces a number of changes for the Steam metadata version, and probably similar changes for other platforms as well. Please be aware that I am working on the necessary changes, but like most things this does take time.

I have opened this as the new "main" issue for this version as I see there are already a number of open issues all with the usual string of "when are we going to get an update" messages. I'd like to keep it all in the one place.

Thanks for your patience!

**Comment by goatfungus** [comment]
OK, first pass is ready (I think)... hopefully those on Steam should now be able to open/edit their save files.

Please post here if you have further errors with this version.

**Comment by andriotisnikos1** [comment]
you're a legend. thanks a ton

**Comment by Uroag** [comment]
Nice work, altho I can't save changes... or moreso I can, but it seems to mess thins up.

Here's the log:

`INFO] Setting BaseContext.PlayerStateData.PersistentPlayerBases[13].Objects[97].Position: ARRAY[3]
[INFO] Formatting JSON...
[INFO] Loading saves for Slot 3...
[INFO] Finished.
[INFO] Reading metadata for save6.hg
[WARNING] cannot read file metadata: mf_save6.hg
[WARNING] java.io.IOException: Invalid metadata header: 9a6f6f8d
	at nomanssave.fI.a(Unknown Source)
	at nomanssave.fI.b(Unknown Source)
	at nomanssave.fP.<init>(Unknown Source)
	at nomanssave.fL.<init>(Unknown Source)
	at nomanssave.fI.W(Unknown Source)
	at nomanssave.fm.run(Unknown Source)
`

**Comment by HQuest** [comment]
> OK, first pass is ready (I think)... hopefully those on Steam should now be able to open/edit their save files.

Save game opens, but as expected, plenty of name mapping not found warning messages. What would the side effects be if the save is modified by the editor while those mappings are not recognized? Would they be removed from the save or preserved as is, until the editor is aware and such mappings can be adjusted?

**Comment by Mioizumaki** [comment]
Account unlocks don't seem to work. They don't show up after selecting them even with going offline before starting the game.

**Comment by wellthathappened** [comment]
This was wildly fast wow, thank you.

**Comment by Thonkpng** [comment]
> Account unlocks don't seem to work. They don't show up after selecting them even with going offline before starting the game.

I am having the same issue with this save editor and NomNom's as well. I've tried selecting the rewards on the account side and save side and I either am met with the rewards still be locked or being previously collected.

**Comment by goatfungus** [comment]
There is a known issue with the new metadata format.... I'm trying to resolve now. Please be patient.

**Comment by goatfungus** [comment]
OK, the latest version 1.17.1 should fix all outstanding issues with the metadata format on Steam. This issue caused saves to not be recognized by the editor after saving. The bug has pretty much been there forever, it's just that the file size of the new metadata file has never highlighted it until now. Weird!

**Comment by wellthathappened** [comment]
Just repeated the steps in the previous release (1.17) that caused metadata read issues and haven't encountered another error. Thank you for the rapid fixes my goodness.

**Comment by goatfungus** [comment]
> > OK, first pass is ready (I think)... hopefully those on Steam should now be able to open/edit their save files.
> 
> Save game opens, but as expected, plenty of name mapping not found warning messages. What would the side effects be if the save is modified by the editor while those mappings are not recognized? Would they be removed from the save or preserved as is, until the editor is aware and such mappings can be adjusted?

Name mappings are just areas of the save file that the editor doesn't recognize. They are always preserved in place, so you can safely edit your file without adverse effects. These warnings are usually the last thing I fix, and sometimes I completely ignore them as they are not really a big priority.

**Comment by GithubUser00009** [comment]
Hi Ive been having issues with the new  1.17.1 version, everytime I try to use it, it gives me the WARNING: Cannot Read File Metadata: mf_accountdata.hg. Ive been unable to modify my account at all

**Comment by Zacas1** [comment]
Sorry if this'll be stupid... was there something majorly different with this update to previous, as this is the first time that my AV has popped up saying it's a threat (some threat called  "ti!d3ee33d97917" that I find no info for)... I'm used to windows popping up a warning about using .exe... this was just the first time the download was flagged so was curious.

**Comment by Callisto649** [comment]
All it's ok TY !

**Comment by Uroag** [comment]
Nice job, works like a charm!

**Comment by steviemch** [comment]
> The new update for No Man's Sky, Worlds Part 1, introduces a number of changes for the Steam metadata version, and probably similar changes for other platforms as well. Please be aware that I am working on the necessary changes, but like most things this does take time.
> 
> I have opened this as the new "main" issue for this version as I see there are already a number of open issues all with the usual string of "when are we going to get an update" messages. I'd like to keep it all in the one place.
> 
> Thanks for your patience!

Hi, as others have said the upcoming expeditions rewards didn't redeem on my save when i tried it with the first update yesterday.  I updated to the latest release just a few minutes ago and now the "Account" tab is greyed out and I can't access it. Is there anything I can do on my end to get it to show or is it just a case of waiting for now? 

Thanks in advance!

**Comment by steviemch** [comment]
Hi, as others have said the upcoming expeditions rewards didn't redeem on my save when i tried it with the first update yesterday. I updated to the latest release just a few minutes ago and now the "Account" tab is greyed out and I can't access it. Is there anything I can do on my end to get it to show or is it just a case of waiting for now?

Thanks in advance!

**Comment by CouncillorCorrina** [comment]
Works for me!  Thanks for all your work to help us, goatfungus.  Please take your time and don't ever feel rushed.  Thanks again!

**Comment by Quaggmar** [comment]
Perhaps i messed up the new download: Here is what i see happening. I can modify the saves and all seems fine. I get into the game via Steam and the changes take effect. What is odd is that when i log out of the game to mode select, go into the editor and make some changes then save those changes when i return to launch the game i do not see the updated date/time for my recent modifications but rather my last exit from the game.

**Comment by steviemch** [comment]
> What is odd is that when i log out of the game to mode select, go into the editor and make some changes then save those changes when i return to launch the game i do not see the updated date/time for my recent modifications but rather my last exit from the game.

Along with my Accounts tab being greyed out and inaccessible, I've also noticed this issue with my saves.

**Comment by jdm12983** [comment]
> Perhaps i messed up the new download: Here is what i see happening. I can modify the saves and all seems fine. I get into the game via Steam and the changes take effect. What is odd is that when i log out of the game to mode select, go into the editor and make some changes then save those changes when i return to launch the game i do not see the updated date/time for my recent modifications but rather my last exit from the game.

One thing to keep in mind: No Man's Sky has auto-saves. If you are still in the game/have your saved open; then game will auto-save every now and then. 

What is probably happening; you have one of the saves opened in the editor - the game auto-saves - and you save changes to the other save file and not the auto save. As there are two save files per save slot.

So, it would be best to save you game; go back to save select; edit and save your game in the editor - making sure to choose the newest file under "Save File" [it will be at the top of the drop-down list]. Make edits, save - then go back to the save select screen in NMS and open the save back up. (Also, don't be on the list of saves - be on the main screen just before that. To make sure it reads the file changes).

**Comment by Quaggmar** [comment]
UPDATE: Experimenting with the issue stated on my earlier post I moved an item in my Exosuit and then saved the game, exited to mode select. Then moved to the Save Editor which offered to auto update my save, which i replied yes to. This portion of the editor works as intended. The issue (confusion on my part) I was running into was how it worked prior to Worlds release where once you made a save editor modification and saved it and then returned to launch the game the Save Game selection would always show the Total Play Time as a dash instead of time played and in the Last Save column it would now reflect the most current timestamp from the save editor. This is not working that way now. The game still reflects the timestamp and time played from the earlier exit of the game to Mode Select.

However, upon making a change in the Save Editor by moving an object to a different slot and saving that, then launching the game even with the incorrect (new) timestamp the item moved does indeed appear in its new slot. 

Conclusion: The saves from the editor are indeed making into the game but it is not updating the current screen data on the Select Save Game screen. I will just have to be cautious on making large editor changes, but they do seem to be taking hold.

Sorry for the long post... Peace and GOATFUNGUS: KUDOS AND A BIG THANK YOU FOR CONTINUING THE UPDATES HERE !!!

**Comment by araminta-de** [comment]
I only registered here to thank you for your work! 🙏🏼

**Comment by HQuest** [comment]
@goatfungus uncertain if this is expected, however when saving changes on your editor, the save timestamp is now not reflected within the game. Edited data is there but it feels tricky to figure out if you will reload the edited save or a game saved save.

Also, naming a save does nothing at the editor. Happy if the description would be read at the save selection. Last but not least, any chance you could label which of the save file pairs is the manual or auto save file.

**Comment by elegault** [comment]
I've combed through the current issues and I think I've stumbled upon a new one for Game Pass reading one save file from the Worlds update where it shows as EMPTY:

![Screenshot 2024-07-24 181938](https://github.com/user-attachments/assets/0f8a4876-8e7f-48b9-91da-9cda5baa4ce6)

[WARNING] Could not read game mode from Slot1Auto
[WARNING] java.io.EOFException: Buffer too small

Here are the logs:
[NMSSaveEditor.log](https://github.com/user-attachments/files/16368367/NMSSaveEditor.log)

**Comment by nmsenjoyer** [comment]
> I've combed through the current issues and I think I've stumbled upon a new one for Game Pass reading one save file from the Worlds update where it shows as EMPTY:
> 
> ![Screenshot 2024-07-24 181938](https://private-user-images.githubusercontent.com/4130365/351908672-0f8a4876-8e7f-48b9-91da-9cda5baa4ce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NjQ0NDgsIm5iZiI6MTcyMTg2NDE0OCwicGF0aCI6Ii80MTMwMzY1LzM1MTkwODY3Mi0wZjhhNDg3Ni04ZTdmLTQ4YjktOTFkYS05Y2RhNWJhYTRjZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMjMzNTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGY5NzI5ZTliMThkZmUxNDQ0NmQ0M2ZlZGZmZmNjNzZkZTdlYjY1NDlkYzAxNDFkMmFmNmYyZTc4YTc3NzkyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jEbUiaw-MvEZVDLKPr7P0qxgMaekz37TuOFW5L-IsIk)
> 
> [WARNING] Could not read game mode from Slot1Auto [WARNING] java.io.EOFException: Buffer too small
> 
> Here are the logs: [NMSSaveEditor.log](https://github.com/user-attachments/files/16368367/NMSSaveEditor.log)

this is the same for me however all of the saves have become empty and unrecognised

**Comment by elidejesus608** [comment]
everything worked fine til todays update for pc/xbox gamepass any update on a fix?

**Comment by DuketheCrusader** [comment]
> > I've combed through the current issues and I think I've stumbled upon a new one for Game Pass reading one save file from the Worlds update where it shows as EMPTY:
> > ![Screenshot 2024-07-24 181938](https://private-user-images.githubusercontent.com/4130365/351908672-0f8a4876-8e7f-48b9-91da-9cda5baa4ce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NjQ0NDgsIm5iZiI6MTcyMTg2NDE0OCwicGF0aCI6Ii80MTMwMzY1LzM1MTkwODY3Mi0wZjhhNDg3Ni04ZTdmLTQ4YjktOTFkYS05Y2RhNWJhYTRjZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMjMzNTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGY5NzI5ZTliMThkZmUxNDQ0NmQ0M2ZlZGZmZmNjNzZkZTdlYjY1NDlkYzAxNDFkMmFmNmYyZTc4YTc3NzkyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jEbUiaw-MvEZVDLKPr7P0qxgMaekz37TuOFW5L-IsIk)
> > [WARNING] Could not read game mode from Slot1Auto [WARNING] java.io.EOFException: Buffer too small
> > Here are the logs: [NMSSaveEditor.log](https://github.com/user-attachments/files/16368367/NMSSaveEditor.log)
> 
> this is the same for me however all of the saves have become empty and unrecognised

it happens to any save game/autosave made post-5.0 is saved differently or something about it is different from saves made on previous versions, making them not loadable, on my observations, anyway. hopefully Goatfungus is already aware of this.
