### ISSUE TITLE
Obsolete Java version is listed as a requirement; error on startup when using this version

### ISSUE THREAD

**Issue by NotMrFlibble** [goatfungus/NMSSaveEditor#1055]
Java 8 is obsolete and has long been so; I can not find it in Devuan or Debian at all except for unstable, from which I don't intend to install as I'm running mostly Devuan stable – for one thing, there is potential for package versions conflict) and for a version intended for use with CUDA, which isn't relevant or even useable here.

The (outdated) `openjdk-8-jre` which I have available here breaks NMSSaveEditor anyway:
```
Initializing environment...
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
	at javax.swing.RepaintManager.<clinit>(RepaintManager.java:238)
	at javax.swing.UIManager.initialize(UIManager.java:1464)
	at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)
	at javax.swing.UIManager.getLookAndFeel(UIManager.java:492)
	at com.formdev.flatlaf.FlatLaf.initialize(FlatLaf.java:255)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:538)
	at nomanssave.aH.V(Unknown Source)
	at nomanssave.aH.init(Unknown Source)
	at nomanssave.Application.main(Unknown Source)
```
This is despite the fact that `libatk-wrapper-java` (which provides the necessary jar file) is installed.

**However**, it *does* work with the current default Java (`openjdk-17-jre`, which can be pulled in by installing `default-jdk`).

I've not tested with Java 21, which is the default in unstable, but I have no reason to think that it wouldn't work.

**Comment by megaUwU-ui** [comment]
try nix package

**Comment by sixwi** [comment]
Java 8 u421 was released July 16, 2024. It is not JDK but is an end user release. Your old JDK is of course outdated but is not what is required. I'm sure the newest JDK is also fine to use.
