### ISSUE TITLE
slot [EMPTY] Game pass

### ISSUE THREAD

**Issue by zowyck** [goatfungus/NMSSaveEditor#1067]
When trying to edit Game pass profiles, they are blocked

I imagine something changed in the new versions, because I have 1 slot that I can edit but the profile is very old

**Comment by im704** [comment]
Even with this version.  Gamepass/Xbox saves are not loading.  It is finding the correct path... or at least when you identify it... but the slots just show empty after.
Last in game save data is correct, so it's seeing the data, just not loading it.

**Comment by HillBillyBong** [comment]
Same here, all emty.

**Comment by lunchanddinner** [comment]
Yup +1, gamepass PC version empty folders

**Comment by xdast06** [comment]
Gamepass and empty too T-T

**Comment by andreos123** [comment]
same :-(

**Comment by goatfungus** [comment]
Should be all good now. The XBox Game pass version had a change to the save format.

**Comment by lunchanddinner** [comment]
> Should be all good now. The XBox Game pass version had a change to the save format.

Still getting an empty folder with the latest release, any idea why?

![Screenshot 2024-09-15 125430](https://github.com/user-attachments/assets/d61a59a0-0fd4-4e82-b755-9e0fd37cee89)

**Comment by BetaTesterMKII** [comment]
They show for me but the editing is broken on windows/xbox version, works on steam from what I've seen.

C:\Users\"YourUserName"\AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs\"WhateverTheFolderNameIs"\containers.index

That is where your saves are

**Comment by FlorentP42** [comment]
I just started having this error today on the Steam version after updating the editor for the RELICS version :/

It seems to only affect my Creative and Permadeath saves though, not my normal saves : 

![Image](https://github.com/user-attachments/assets/37049aaf-343f-469b-a481-c70b99bcfa96)

Trying to open one of those "empty" saves result in the following stack trace : 

```
Reading account data...
Loading saves for Slot 1...
Reading save file...
  Slot: Slot 1 - [EMPTY]
  Filename: save.hg
Finished.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at nomanssave.gt.<init>(Unknown Source)
        at nomanssave.gt.<init>(Unknown Source)
        at nomanssave.gz.<init>(Unknown Source)
        at nomanssave.gz.w(Unknown Source)
        at nomanssave.Application.l(Unknown Source)
        at nomanssave.Application.e(Unknown Source)
        at nomanssave.Application.a(Unknown Source)
        at nomanssave.D.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by FlorentP42** [comment]
@wkitty42 My bad, I think I actually commented on the wrong topic, I meant to comment on #1120, which is actually not specific to Game pass.
