### ISSUE TITLE
Trouble restoring from backup for gamepass version

### ISSUE THREAD

**Issue by yeetmageets** [goatfungus/NMSSaveEditor#1080]
How do I restore my save from the backups in the backup folder?

**Comment by Devilin-Pixy** [comment]
In the Save Editor, you can just use the drop-down for the selected save slot, to then select the stored backup (.zip), after which you can click Save Changes to restore to it.

**Comment by yeetmageets** [comment]
I figured thats how its supposed to work. For some reason when I select any backup in that dropdown I get "Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException"

**Comment by yeetmageets** [comment]
in the cmd window that is and am unable to do anything further

**Comment by Devilin-Pixy** [comment]
Perhaps the saved backup can not be restored due to recent changes to the file structure, not sure. It would be helpful to provide the full log that contains the exception handling. Check the tool's location for it.

Not quite sure what the backup would look like for Game Pass, knowing Microsoft deals with the save file location quite differently than what I am used to. It may therefor not be an easy unzip to replace in original save file location.

**Comment by yeetmageets** [comment]
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD5263120474B"
[DEBUG] suffix: 218
[DEBUG] unknown1: 1
[DEBUG] containerPath: D3BC6A31455A470EB953D187AB84A8D7
[DEBUG] timestamp: Sat Sep 14 20:31:40 CDT 2024
[DEBUG] totalSize: 643741
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD59C89E11F5A"
[DEBUG] suffix: 8
[DEBUG] unknown1: 1
[DEBUG] containerPath: D3BC6A31455A470EB953D187AB84A8D7
[DEBUG] timestamp: Sun Sep 15 10:32:04 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 75:32
[DEBUG] compressed: 650373
[DEBUG] description: Aboard the Space Anomaly
[DEBUG] unknown2: 2
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD59FD298EBBC"
[DEBUG] suffix: 216
[DEBUG] unknown1: 1
[DEBUG] containerPath: D3BC6A31455A470EB953D187AB84A8D7
[DEBUG] timestamp: Sun Sep 15 11:01:30 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 75:32
[DEBUG] compressed: 640433
[DEBUG] description: Aboard the Space Anomaly
[DEBUG] unknown2: 2
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD5AAD2F28FBE"
[DEBUG] suffix: 3
[DEBUG] unknown1: 1
[DEBUG] containerPath: ADFCC2CE795D4CC29950EF494A50D424
[DEBUG] timestamp: Sun Sep 15 12:19:22 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD5B528B6A427"
[DEBUG] suffix: 3
[DEBUG] unknown1: 1
[DEBUG] containerPath: 2414FACF59984E65B4ADF7C33A09D123
[DEBUG] timestamp: Sun Sep 15 13:34:10 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD5B528B6A427"
[DEBUG] suffix: 3
[DEBUG] unknown1: 1
[DEBUG] containerPath: 2414FACF59984E65B4ADF7C33A09D123
[DEBUG] timestamp: Sun Sep 15 13:34:10 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD5B528B6A427"
[DEBUG] suffix: 3
[DEBUG] unknown1: 1
[DEBUG] containerPath: 2414FACF59984E65B4ADF7C33A09D123
[DEBUG] timestamp: Sun Sep 15 13:34:10 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD5B528B6A427"
[DEBUG] suffix: 3
[DEBUG] unknown1: 1
[DEBUG] containerPath: 2414FACF59984E65B4ADF7C33A09D123
[DEBUG] timestamp: Sun Sep 15 13:34:10 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD5B528B6A427"
[DEBUG] suffix: 3
[DEBUG] unknown1: 1
[DEBUG] containerPath: 2414FACF59984E65B4ADF7C33A09D123
[DEBUG] timestamp: Sun Sep 15 13:39:17 CDT 2024
[DEBUG] totalSize: 640731
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 640451
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD5B528B6A427"
[DEBUG] suffix: 3
[DEBUG] unknown1: 1
[DEBUG] containerPath: 2414FACF59984E65B4ADF7C33A09D123
[DEBUG] timestamp: Sun Sep 15 13:39:20 CDT 2024
[DEBUG] totalSize: 640731
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD5B528B6A427"
[DEBUG] suffix: 3
[DEBUG] unknown1: 1
[DEBUG] containerPath: 2414FACF59984E65B4ADF7C33A09D123
[DEBUG] timestamp: Sun Sep 15 13:39:20 CDT 2024
[DEBUG] totalSize: 640731
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD5B528B6A427"
[DEBUG] suffix: 3
[DEBUG] unknown1: 1
[DEBUG] containerPath: 2414FACF59984E65B4ADF7C33A09D123
[DEBUG] timestamp: Sun Sep 15 13:39:20 CDT 2024
[DEBUG] totalSize: 640731
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD677A2163D04"
[DEBUG] suffix: 8
[DEBUG] unknown1: 1
[DEBUG] containerPath: 15EC467D04C84627B4CD5D343C27A7E8
[DEBUG] timestamp: Mon Sep 16 12:46:13 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD677A2163D04"
[DEBUG] suffix: 8
[DEBUG] unknown1: 1
[DEBUG] containerPath: 15EC467D04C84627B4CD5D343C27A7E8
[DEBUG] timestamp: Mon Sep 16 12:46:13 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD677A2163D04"
[DEBUG] suffix: 8
[DEBUG] unknown1: 1
[DEBUG] containerPath: 15EC467D04C84627B4CD5D343C27A7E8
[DEBUG] timestamp: Mon Sep 16 12:46:13 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD677A2163D04"
[DEBUG] suffix: 8
[DEBUG] unknown1: 1
[DEBUG] containerPath: 15EC467D04C84627B4CD5D343C27A7E8
[DEBUG] timestamp: Mon Sep 16 12:46:13 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD677A2163D04"
[DEBUG] suffix: 8
[DEBUG] unknown1: 1
[DEBUG] containerPath: 15EC467D04C84627B4CD5D343C27A7E8
[DEBUG] timestamp: Mon Sep 16 12:46:13 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD677A2163D04"
[DEBUG] suffix: 8
[DEBUG] unknown1: 1
[DEBUG] containerPath: 15EC467D04C84627B4CD5D343C27A7E8
[DEBUG] timestamp: Mon Sep 16 12:46:13 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD677A2163D04"
[DEBUG] suffix: 8
[DEBUG] unknown1: 1
[DEBUG] containerPath: 15EC467D04C84627B4CD5D343C27A7E8
[DEBUG] timestamp: Mon Sep 16 12:46:13 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DCD677A2163D04"
[DEBUG] suffix: 8
[DEBUG] unknown1: 1
[DEBUG] containerPath: 15EC467D04C84627B4CD5D343C27A7E8
[DEBUG] timestamp: Mon Sep 16 12:46:13 CDT 2024
[DEBUG] totalSize: 650669
[DEBUG] unknown1: 103b
[INFO] version: 1
[INFO] totalPlayTime: 73:10
[DEBUG] compressed: 643445
[DEBUG] description: Aboard Lippop-Goten Station Minor
[DEBUG] unknown2: 1
[INFO] Reading save file...
[INFO] Slot: Slot 1 - NORMAL - Sep 16, 16:59
[INFO] Filename: Slot1Manual
[INFO] Finished.
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
[STDERR] 	at nomanssave.fR.getName(Unknown Source)
[STDERR] 	at nomanssave.fU.getName(Unknown Source)
[STDERR] 	at nomanssave.Application.l(Unknown Source)
[STDERR] 	at nomanssave.Application.f(Unknown Source)
[STDERR] 	at nomanssave.Application.b(Unknown Source)
[STDERR] 	at nomanssave.E.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.Component.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.Component.processEvent(Unknown Source)
[STDERR] 	at java.awt.Container.processEvent(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)
[INFO] Formatting JSON...
[INFO] Writing new save file...
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
[STDERR] 	at nomanssave.fX.b(Unknown Source)
[STDERR] 	at nomanssave.fU.b(Unknown Source)
[STDERR] 	at nomanssave.Application.n(Unknown Source)
[STDERR] 	at nomanssave.Application.b(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[STDERR] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[STDERR] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.Component.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.Component.processEvent(Unknown Source)
[STDERR] 	at java.awt.Container.processEvent(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by yeetmageets** [comment]
You can see it loads the saves fine and then as soon as I select the backup it starts the first [STDERR] line

**Comment by ZataraTMM** [comment]
Did you manage to fix this?

**Comment by yeetmageets** [comment]
Unfortunately I have not

**Comment by yeetmageets** [comment]
To anyone reading I was able to salvage my save thanks to advice from ZataraTMM in another post. The way I was able to fix was to load the messed up save in NomNom save editor and I just added one nanite and then saved. Opened the game selected the save and it loaded right up!

**Comment by TehTarik4Life** [comment]
Hi there, facing same issue here, i was editing save but turn out my save corrupted? It start from a new game when i load the save. And i had no idea how to load the backup file. Really do appreciate it if able to give me a hand here. I have 300hours on the save files..

**Comment by TehTarik4Life** [comment]
Hi there, facing same issue here, i was editing save but turn out my save corrupted? It start from a new game when i load the save. And i had no idea how to load the backup file. I tried to select the wgsbackup file and press save change but nothing happen. Really do appreciate it if able to give me a hand here. I have 300hours on the save files..
