### ISSUE TITLE
Saves showing empty or no name...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [goatfungus/NMSSaveEditor#1120]
Since the last update about two weeks ago I have been unable to identify which save is which in NMSSE. The save selection shows nothing useful. Timestamp, location, nothing. I have avoided using NMSSE for this reason because I do not know if it can damage a modern save. I did start a new save last night and tried editing it with NMSSE and it appeared to work, but the save showed no location or time played or anything in the game. It did load and the one change I made worked, but I am still not sure about the lack of info showing.

![Broken](https://github.com/user-attachments/assets/b126711d-dfae-4ad6-9b43-a71e0e99124b)

That is what I see in the editor now. My gut says that the header is just not being read (new format?) but I have no clue.

**Comment by The-Great-Sephiroth** [comment]
Not sure how to attach an image when editing a post. I uploaded the wrong image last time and am uploading the correct one below. This is what I have seen since 5.20 arrived.
![Broken](https://github.com/user-attachments/assets/cd8920b3-7ed0-4db1-99f7-8543c94d59f9)

**Comment by wkitty42** [comment]
i forget which other issue(s) this was discussed in but if you name your save while in-game, that name will display here... i think there was some talk about possibly displaying the default save name as given by NMS but i'm not sure... there was also some talk of maybe having other data displayed here but these types of selection lists are not really conducive to carrying all of it...

**Comment by The-Great-Sephiroth** [comment]
It displayed information before. It's now simply blank. That's why I reported it. I personally never name my saves. I never had the need to do so.

**Comment by emilio-simoes** [comment]
Had a similar issue, I guess it was related with NMS changing not only the way they sotore saves due to crossed saved but also related with the save cache they store locally. I've already reported this to Hello Games myself but since this is a new issue it may take some time for them to identify it and fix it!

Unfortunately we can't do anything in NMSSE because the author does not allows us to help in any way!!!

Anyhow, trust Hello Games, they will find a fix for this soon, remember it's a small company and they have limited resources, just be patient.

**Comment by meachware** [comment]
No idea why your editor is listing "[Empty]" slots... mine has never done that, like ever. The last update to the Editor resolved an issue I reported, here: https://github.com/goatfungus/NMSSaveEditor/issues/1095

Since that update to the Editor; all my saves in the drop down are listed as "Normal" saves. I name my saves and all my names are displayed properly. However, I have NO Normal saves, I even convert expedition saves to Survival. 

So the last update to the game broke the Editors ability to determine the game "mode" of the save and by default lists them as "Normal".

All my saves report the time and date stamp just fine and when I save changes, it updates correctly.

**Comment by wkitty42** [comment]
> No idea why your editor is listing "[Empty]" slots... mine has never done that, like ever.

because in the image the save3,4,5, and 6.hg files do not exist...
remember,
Slot 1 files are: save.hg and save2.hg
Slot 2 files are: save3.hg and save4.hg <-- missing so "[Empty]"
Slot 3 files are: save5.hg and save6.hg <-- missing so "[Empty]"
Slot 4 files are: save7.hg and save8.hg
etc...

why they skipped "1" in the first slot's first filename i don't know... maybe it was the only save file early on before the second was introduced and they never updated the name? idk but there it is...

the key factor for showing empty slots is the gap between saveX.hg filenames... NMS does this, too, but it also now presents the slots in order from most recently played to least recently played...

yes, in the above examples, the mf_saveX.hg files are included... i was keeping the list short and i only wanted to respond to this one comment about empty slots...

**Comment by meachware** [comment]
I routinely make or edit my saves and put them on Slot 15. I almost never go beyond slot 10 w/my normal saves. Hopefully I can upload this image that clearly demonstrates what I said
![Slot15-NMSSE](https://github.com/user-attachments/assets/69d72a4b-a1ad-439e-9089-56ee7ac22bf0)

**Comment by emilio-simoes** [comment]
@meachware not sure why the prerequisite is still Java 8! That's a like pre-historic version of Java, current LTS version is 21 and the last stable release is (I think) version 23... Forcing users to use an old version is a security issue!!! You should always be using the most recent version of Java, either LTS (long time support which gets fixes for a longer period) or the latest version of the runtime (https://www.java.com/releases/)
Any obsolete version is a risk on your machine because it exposes you to identified vulnerabilities known as CVE's and openly exposed on the web for you to known the risks you take: https://www.cvedetails.com/vulnerability-list/vendor_id-93/product_id-19117/oracle-jre.html

YOU SHOULD NOT BE USING JAVA 8!

**Comment by LockNessMonster1** [comment]
True story, when dealing with Java apps always make sure you're using the latest version! New versions fix security issues, any app using Java should be aware of this, it's common sense

**Comment by meachware** [comment]
Thanks for the concern and info
Indeed v8 Update 371 was behind, so I updated it - straight from the Java.com site:
"Version 8 Update 431 (filesize: 66.03 MB) [Why is Java 8 recommended](https://www.java.com/download/why-java-8-recommended.html)?

Release date: October 15, 2024"

This is for the runtime environment (JRE) and NOT for the JDK. I have no need for the JDK and only require the JRE.

**Comment by emilio-simoes** [comment]
@meachware the link you provide fo [Why is Java 8 recommended](https://www.java.com/download/why-java-8-recommended.html) has been posted by Oracle which kind of "bought" Java some years ago and hustled a war against anyone trying to use use Java.

Being Java at the time an Open Source project already decent people fought back and Oracle Java is no longer the reference implementation and currently there are much successful fully compatible Java implementations maintained by top companies like Microsoft, AWS, JetBrains, Red Hat, Adoptium being this last one probably the most used open source one since is backed by the [Eclipse Foundation(https://adoptium.net/temurin/releases/).

Not sure why Oracle perpetuates the idea that Java 8 is good for you (maybe they are bad loosers...), but believe me, it's not. Update you JRE to the latest LTS (Long Time Support) version from the implementation of you're choice. Just drop Oracle, take it from a 15+ year Java developer!!!

**Comment by emilio-simoes** [comment]
By the way, just for reference, the 2 reference toolkits for programming applications Java for the Web, [Quarkus](https://code.quarkus.io/) and [Spring](https://start.spring.io/) do not support any Java version prior to Java 17!!! These are the most used toolkits out there. Thousands of enterprise applications use these toolkits on hundreds of thousand of applications and they are successful.

It surely must be a good reason for this!

**Comment by The-Great-Sephiroth** [comment]
> > No idea why your editor is listing "[Empty]" slots... mine has never done that, like ever.
> 
> because in the image the save3,4,5, and 6.hg files do not exist... remember, Slot 1 files are: save.hg and save2.hg Slot 2 files are: save3.hg and save4.hg <-- missing so "[Empty]" Slot 3 files are: save5.hg and save6.hg <-- missing so "[Empty]" Slot 4 files are: save7.hg and save8.hg etc...
> 
> why they skipped "1" in the first slot's first filename i don't know... maybe it was the only save file early on before the second was introduced and they never updated the name? idk but there it is...
> 
> the key factor for showing empty slots is the gap between saveX.hg filenames... NMS does this, too, but it also now presents the slots in order from most recently played to least recently played...
> 
> yes, in the above examples, the mf_saveX.hg files are included... i was keeping the list short and i only wanted to respond to this one comment about empty slots...

You are incorrect. Those saves exist and can be opened in NomNom and NMSSE. Now do you understand why I filed the bug report? Those two saves exist and are playable. All of my saves show up correctly in NomNom, but NomNom destroys things (I reported some bugs to them tonight) so I don't touch it.

**Comment by emilio-simoes** [comment]
I'ts the first time I'm hearing about NomNon but this just proves all my point 😂 

Although NomNon is "open source" all the commits are done by the same guy 😂, which is kind of the same of what's happening on this repo with the (big) difference that the "other guy" is not hiding what's is doing!

Both of these tools have done bad one day or the other, if you want to point fingers point fingers at the guy that is hiding what's is doing? At leat NomNom can receive tips on the things he can improve!

Have you tried to drop a hint on his repo pointing to what we might be doing wrong? Like productive stuff, like "this line in you're code is doing this"? At least there you can do that and I'm sure he would look into it to check if it would fix the problem!!!

**Comment by LockNessMonster1** [comment]
![Screenshot_6](https://github.com/user-attachments/assets/cea758b1-39a4-43d6-897f-2375cb70b48b)

Damn @The-Great-Sephiroth just took a look at your profile, are you realy proud of these stuff? is this your life achievements? Because UAU...

* Atari 400 - Fantastic if you're a museum guy who can still show the little kids how stuff was done in the old years!
* Basic and QuickBasic - I Honestly don't have a clue on which one I should laugh the most since they are both so equally bad 😂 
* C a and C++ is were you redeem yourself since these are real world languages although from your history is kind of unlikely you have done something really productive with it!
* Pascal... Ok, this is one of the oldies, I've learned programing in Pascal myself and them moved to Delphi for a few moments until I discover .NET Framework, it was a good language but it had it's run
* PHP (I'm trying so hard no to laugh) 😂  it's just most likely the worst web language ever created....
* HTML4 😂😂😂😂😂😂😂😂😂😂😂😂 oh god! I have no words for this one, no one has been using HTML4 for more than 20 years, how old are you? 😂😂😂

**Comment by LockNessMonster1** [comment]
Then I could go with CSS3 but how you would know bout that using HTML4? 😂😂😂

And you just finish with "javascript and more", what ever that means, but I'm curious for you to tell us what that "more" means!!! 🤭 

We are all anxious just to know what the great Sephiroth as to teach us young dudes! :)

**Comment by emilio-simoes** [comment]
HTML4? Is that even a thing used by anyone? Id this a record of what he knows or of how outdated he is???

**Comment by FlorentP42** [comment]
I just started having this error today on the Steam version after updating the editor for the 1.18.1 (RELICS) version, while playing NMS 5.64 :/

It seems to only affect my Creative and Permadeath saves though, not my normal saves : 

![Image](https://github.com/user-attachments/assets/37049aaf-343f-469b-a481-c70b99bcfa96)

Trying to open one of those "empty" saves result in the following stack trace : 

```
Reading account data...
Loading saves for Slot 1...
Reading save file...
  Slot: Slot 1 - [EMPTY]
  Filename: save.hg
Finished.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at nomanssave.gt.<init>(Unknown Source)
        at nomanssave.gt.<init>(Unknown Source)
        at nomanssave.gz.<init>(Unknown Source)
        at nomanssave.gz.w(Unknown Source)
        at nomanssave.Application.l(Unknown Source)
        at nomanssave.Application.e(Unknown Source)
        at nomanssave.Application.a(Unknown Source)
        at nomanssave.D.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```
