### ISSUE TITLE
[INFO] Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by bhseo** [goatfungus/NMSSaveEditor#113]
Hello,
Having an issue with the json editor, but everything else seems to be working for the particular save file. Im able to use the json editor for a newer save game, the only difference i can tell between the files is the size. Issues: 6.811KB, working:1.22MB not sure if that helps!

Thanks for all the effort!

Pasted the log below:
[INFO] Mem Usage: 79/260 MB
[INFO] Latest version: "1.5.22"
[INFO] Current version: "1.5.22"
[INFO] Loading saves for Slot 1...
[INFO] Reading save file...
[INFO]   Path: C:\Users\xxxxxx\AppData\Roaming\HelloGames\NMS\XXXX
[INFO]   Slot: Slot 1 - NORMAL
[INFO]   Filename: save.hg
[INFO] Parsing JSON...
[INFO] Finished.
[INFO] Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
[INFO] 	at javax.swing.text.GapContent.createPosition(GapContent.java:249)
[INFO] 	at javax.swing.text.AbstractDocument.createPosition(AbstractDocument.java:829)
[INFO] 	at javax.swing.text.AbstractDocument$LeafElement.<init>(AbstractDocument.java:2505)
[INFO] 	at javax.swing.text.AbstractDocument.createLeafElement(AbstractDocument.java:1275)
[INFO] 	at javax.swing.text.PlainDocument.insertUpdate(PlainDocument.java:200)
[INFO] 	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:745)
[INFO] 	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
[INFO] 	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
[INFO] 	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
[INFO] 	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1669)
[INFO] 	at nomanssave.cB.valueChanged(Unknown Source)
[INFO] 	at javax.swing.JTree.fireValueChanged(JTree.java:2927)
[INFO] 	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3391)
[INFO] 	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
[INFO] 	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
[INFO] 	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
[INFO] 	at javax.swing.JTree.setSelectionPaths(JTree.java:1647)
[INFO] 	at javax.swing.JTree.setSelectionRows(JTree.java:1729)
[INFO] 	at javax.swing.JTree.setSelectionRow(JTree.java:1704)
[INFO] 	at nomanssave.cB.a(Unknown Source)
[INFO] 	at nomanssave.cB.a(Unknown Source)
[INFO] 	at nomanssave.Application.o(Unknown Source)
[INFO] 	at nomanssave.Application.t(Unknown Source)
[INFO] 	at nomanssave.H.actionPerformed(Unknown Source)
[INFO] 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
[INFO] 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
[INFO] 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
[INFO] 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
[INFO] 	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
[INFO] 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
[INFO] 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
[INFO] 	at java.awt.Component.processMouseEvent(Component.java:6533)
[INFO] Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
[INFO] 	at java.util.Arrays.copyOf(Arrays.java:3332)
[INFO] 	at java.lang.StringCoding.safeTrim(StringCoding.java:89)
[INFO] 	at java.lang.StringCoding.access$100(StringCoding.java:50)
[INFO] 	at java.lang.StringCoding$StringDecoder.decode(StringCoding.java:154)
[INFO] 	at java.lang.StringCoding.decode(StringCoding.java:193)
[INFO] 	at java.lang.String.<init>(String.java:426)
[INFO] 	at nomanssave.storage.b.c(Unknown Source)
[INFO] 	at nomanssave.storage.b.d(Unknown Source)
[INFO] 	at nomanssave.storage.b.f(Unknown Source)
[INFO] 	at nomanssave.storage.f.aK(Unknown Source)
[INFO] 	at nomanssave.storage.f.toString(Unknown Source)
[INFO] 	at javax.swing.plaf.basic.BasicComboBoxRenderer.getListCellRendererComponent(BasicComboBoxRenderer.java:121)
[INFO] 	at com.sun.java.swing.plaf.windows.WindowsComboBoxUI$WindowsComboBoxRenderer.getListCellRendererComponent(WindowsComboBoxUI.java:535)
[INFO] 	at com.sun.java.swing.plaf.windows.WindowsComboBoxUI.paintCurrentValue(WindowsComboBoxUI.java:290)
[INFO] 	at javax.swing.plaf.basic.BasicComboBoxUI.paint(BasicComboBoxUI.java:904)
[INFO] 	at com.sun.java.swing.plaf.windows.WindowsComboBoxUI.paint(WindowsComboBoxUI.java:218)
[INFO] 	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
[INFO] 	at javax.swing.JComponent.paintComponent(JComponent.java:780)
[INFO] 	at javax.swing.JComponent.paint(JComponent.java:1056)
[INFO] 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
[INFO] 	at javax.swing.JComponent.paint(JComponent.java:1065)
[INFO] 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
[INFO] 	at javax.swing.JComponent.paint(JComponent.java:1065)
[INFO] 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
[INFO] 	at javax.swing.JComponent.paint(JComponent.java:1065)
[INFO] 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
[INFO] 	at javax.swing.JComponent.paint(JComponent.java:1065)
[INFO] 	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
[INFO] 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
[INFO] 	at javax.swing.JComponent.paint(JComponent.java:1065)
[INFO] 	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
[INFO] 	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
[INFO] Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
[INFO] 	at java.util.Arrays.copyOf(Arrays.java:3332)
[INFO] 	at java.lang.StringCoding.safeTrim(StringCoding.java:89)
[INFO] 	at java.lang.StringCoding.access$100(StringCoding.java:50)
[INFO] 	at java.lang.StringCoding$StringDecoder.decode(StringCoding.java:154)
[INFO] 	at java.lang.StringCoding.decode(StringCoding.java:193)
[INFO] 	at java.lang.String.<init>(String.java:426)
[INFO] 	at nomanssave.storage.b.c(Unknown Source)
[INFO] 	at nomanssave.storage.b.d(Unknown Source)
[INFO] 	at nomanssave.storage.b.f(Unknown Source)
[INFO] 	at nomanssave.storage.f.aK(Unknown Source)
[INFO] 	at nomanssave.storage.f.toString(Unknown Source)
[INFO] 	at javax.swing.plaf.basic.BasicComboBoxRenderer.getListCellRendererComponent(BasicComboBoxRenderer.java:121)
[INFO] 	at com.sun.java.swing.plaf.windows.WindowsComboBoxUI$WindowsComboBoxRenderer.getListCellRendererComponent(WindowsComboBoxUI.java:535)
[INFO] 	at com.sun.java.swing.plaf.windows.WindowsComboBoxUI.paintCurrentValue(WindowsComboBoxUI.java:290)
[INFO] 	at javax.swing.plaf.basic.BasicComboBoxUI.paint(BasicComboBoxUI.java:904)
[INFO] 	at com.sun.java.swing.plaf.windows.WindowsComboBoxUI.paint(WindowsComboBoxUI.java:218)
[INFO] 	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
[INFO] 	at javax.swing.JComponent.paintComponent(JComponent.java:780)
[INFO] 	at javax.swing.JComponent.paint(JComponent.java:1056)
[INFO] 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
[INFO] 	at javax.swing.JComponent.paint(JComponent.java:1065)
[INFO] 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
[INFO] 	at javax.swing.JComponent.paint(JComponent.java:1065)
[INFO] 	at javax.swing.JComponent.paintChildren(JComponent.java:889)
[INFO] 	at javax.swing.JComponent.paint(JComponent.java:1065)
[INFO] 	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
[INFO] 	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
[INFO] 	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
[INFO] 	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
[INFO] 	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
[INFO] 	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
[INFO] 	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
[INFO] Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
[INFO] Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
[INFO] Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

**Comment by bhseo** [comment]
found the same issue posted earlier thread my bad!
