### ISSUE TITLE
Save error, will not save changes

### ISSUE THREAD

**Issue by JQP18z** [goatfungus/NMSSaveEditor#129]
For the last 3 patches I have not been able to use the editor. I open it just fine, load my save just fine and can make changes. When it comes time to save the changes I get the error: "there was an error saving file". Ive always used the .jar. As per the read me I tried using the 4g executable. That never works and says: "Invalid maximum heap size: -Xmx4g Could not create java virtual machine". I would give you a log file but it no longer generates one when i get an error as it used too.

new error now also says

Warning: name mapping not found: sH1
Warning: name mapping not found: D6b

**Comment by JQP18z** [comment]
It finally created a log


[INFO] Starting Editor...
[DEBUG] Windows font size detected: 11
[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_181
[DEBUG] Mem Usage: 16/260 MB
[DEBUG] Latest version: "1.5.25"
[DEBUG] Current version: "1.5.25"
[INFO] Loading slots: C:\Users\CFL\AppData\Roaming\HelloGames\NMS\st_76561198015658426
[INFO] Moving backup files...
[INFO] Loading saves for Slot 5...
[INFO] Reading save file...
[INFO] Path: C:\Users\CFL\AppData\Roaming\HelloGames\NMS\st_76561198015658426
[INFO] Slot: Slot 5 - CREATIVE
[INFO] Filename: save10.hg
[INFO] Parsing JSON...
[INFO] Finished.
[INFO] Formatting JSON...
[INFO] Creating backup...
[ERROR] Could not write save file: save10.hg
[ERROR] java.io.FileNotFoundException: backups\backup10.1535896219638.zip (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at nomanssave.storage.b.a(Unknown Source)
	at nomanssave.storage.b.a(Unknown Source)
	at nomanssave.storage.m.j(Unknown Source)
	at nomanssave.Application.l(Unknown Source)
	at nomanssave.Application.i(Unknown Source)
	at nomanssave.y.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
[ERROR] Could not save configuration file
[ERROR] java.io.FileNotFoundException: NMSSaveEditor.conf (The system cannot find the file specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at nomanssave.Application.e(Unknown Source)
	at nomanssave.Application.k(Unknown Source)
	at nomanssave.t.windowClosing(Unknown Source)
	at java.awt.AWTEventMulticaster.windowClosing(Unknown Source)
	at java.awt.Window.processWindowEvent(Unknown Source)
	at javax.swing.JFrame.processWindowEvent(Unknown Source)
	at java.awt.Window.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by goatfungus** [comment]
When the editor saves a file it does the following:
- Creates a backup file
- Saves the save file

In your case it cannot create the backup file.

My question for you is: did you copy the editor files out of the zip file that it was packaged in (step 2 of the instructions), or are you running it inside the zip file? The editor cannot create the backup file if the editor app is inside a zip file.

**Comment by goatfungus** [comment]
Try downloading the new self-extracting installer from here:
[NMSSaveEditor.exe](../raw/master/NMSSaveEditor.exe)

**Comment by JQP18z** [comment]
I was always extracting it to a folder on my desktop and its always worked. I get the same error with the exe you posted. 

I was fine until I tried the experimental branch of the game. Ever since then this editor wont work. Ive even reinstalled the game.

**Comment by goatfungus** [comment]
These errors indicate that the editor is not able to write to the directory where the save editor app is installed:
java.io.FileNotFoundException: NMSSaveEditor.conf (The system cannot find the file specified)
java.io.FileNotFoundException: backups\backup10.1535896219638.zip (The system cannot find the path specified)

So to fix this, you need to either run one of the batch files instead of the jar directly, or make sure the working directory is not read-only.

**Comment by goatfungus** [comment]
What i find really odd about this is that it can create a log file, but can't create a config file in exactly the same location. That can't be related to the editor itself as it uses exactly the same I/O methods for both files. Perhaps your system setup is restricting what it allows Java to do, but that is something I don't have control over.

**Comment by goatfungus** [comment]
@JQP18z Just wondering if you would be able to try this version. I have added some extra directory checking that might help.
[NMSSaveEditor.zip](https://github.com/goatfungus/NMSSaveEditor/files/2346724/NMSSaveEditor.zip)

**Comment by gj4297** [comment]
Have the same probrem
just can not change the floder from " read-only "
every time i change it ,
it will automatic go back to " read only"

**Comment by gj4297** [comment]
The save folder from (*includeall file inside)
C:\Users\User\AppData\Roaming\HelloGames\NMS\st_XXXXXXXXXX
It work when i separate the file one by one
but when i put all file in to same folder
the whole folder become "" read-only "

**Comment by goatfungus** [comment]
I have no idea.... we aren't actually talking about your main saves directory here, but the one where the editor stores backups, log, and config files. If you're having issues with the main save directory, I would suggest its something to do with your system.

**Comment by gj4297** [comment]
Oops my bad……
and ty for help

**Comment by goatfungus** [comment]
I have added some extra detection in the latest version, 1.5.26, so most of these issues should be solved now.
