### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException

### ISSUE THREAD

**Issue by charliebanks** [goatfungus/NMSSaveEditor#174]
Heya - I'm getting some errors when loading the Game slot. It looks like it will partially load some of the data and then fail. I've pasted the error log here.

I beleive i have everything up to date. 
Java - 8.191
NMS Save Editor - 1.5.37

any ideas?

Thanks! :)

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at nomanssave.aA.a(Unknown Source)
        at nomanssave.Application.j(Unknown Source)
        at nomanssave.Application.i(Unknown Source)
        at nomanssave.Application.m(Unknown Source)
        at nomanssave.v.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Walmarx** [comment]
I am also getting this error, but as far as I can tell the save I am attempting to open is from the current version of the game (1.77).

The save selection gets as far as displaying "Slot 1 - [EMPTY]". I am attempting to use this tool to fix my location; I am stuck in a CE-Event System with no realistic way out conventionally. 

My save directory contains four *.hg files:
mf_save.hg  
mf_save2.hg
save.hg
save2.hg

The first two are only 104 bytes in size, whereas the last two are 1.17 mb. I am able to load both single player and multiplayer saves without issue in-game (positional data notwithstanding).

Thanks so much for your brilliant efforts goatfungus!

**Comment by charliebanks** [comment]
Hey @Walmarx ,

I was getting the error because I had multiple saves slots and I thought I was loading my current save, but actually I was loading a slot I had last used about a year ago. 

I _think_ the save you want to edit needs to have been loaded and saved using the current game version. i.e. Even if you're on v1.77, you might still have save files that were last saved on an earlier version and would produce this error. To fix it you would need to load and save in-game to ensure its on the current version. Do you think that might be the case for you?

**Comment by Walmarx** [comment]
Thanks for the response charliebanks, unfortunately that isn't the case for me as I have no saves prior to a week ago. I'm about 35 hours into my first playthrough : /

**Comment by Walmarx** [comment]
Eureka! I was trying to load the save into the Save Editor across drives (silly me). Once I put the working directory of the Editor into the \st_xxxxxxxxxxxxx folder, it loaded my file with no trouble. Its bizarre that would produce the same logged error as an old save file... Nonetheless, thanks again!
