### ISSUE TITLE
All tabs except "main" and "Exosuit" are greyed out, along with the Edit button, and save functions

### ISSUE THREAD

**Issue by WastelandWizard** [goatfungus/NMSSaveEditor#180]
I can't edit anything except for health/ units etc. it won't even let me use advanced edit, it's probably something simple knowing me but I can't figure it out

**Comment by DavidAlt** [comment]
I'm also having this issue. Here's the log from when I tried to change my units.

Initializing environment...
Starting Editor...
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at nomanssave.ci.getSize(Unknown Source)
        at javax.swing.JComboBox.getSelectedIndex(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup.configureList(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup.<init>(Unknown Source)
        at javax.swing.plaf.basic.BasicComboBoxUI.createPopup(Unknown Source)
        at com.sun.java.swing.plaf.windows.WindowsComboBoxUI.createPopup(Unknown Source)
        at javax.swing.plaf.basic.BasicComboBoxUI.installUI(Unknown Source)
        at com.sun.java.swing.plaf.windows.WindowsComboBoxUI.installUI(Unknown Source)
        at javax.swing.JComponent.setUI(Unknown Source)
        at javax.swing.JComboBox.setUI(Unknown Source)
        at javax.swing.JComboBox.updateUI(Unknown Source)
        at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
        at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
        at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
        at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
        at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
        at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
        at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
        at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
        at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
        at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
        at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
        at javax.swing.SwingUtilities.updateComponentTreeUI(Unknown Source)
        at com.sun.java.swing.plaf.windows.DesktopProperty.updateWindowUI(Unknown Source)
        at com.sun.java.swing.plaf.windows.DesktopProperty.updateAllUIs(Unknown Source)
        at com.sun.java.swing.plaf.windows.DesktopProperty.access$000(Unknown Source)
        at com.sun.java.swing.plaf.windows.DesktopProperty$1.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(Unknown Source)
        at java.awt.Dialog.show(Unknown Source)
        at javax.swing.JFileChooser.showDialog(Unknown Source)
        at javax.swing.JFileChooser.showOpenDialog(Unknown Source)
        at nomanssave.Application.h(Unknown Source)
        at nomanssave.Application.q(Unknown Source)
        at nomanssave.T.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Loading slots: C:\Users\david\AppData\Roaming\HelloGames\NMS\st_76561198035039560
Moving backup files...
Loading saves for Slot 2...
Reading save file...
  Slot: Slot 2 - SURVIVAL
  Filename: save3.hg
Parsing JSON...
  using name mappings: NMS 1.76
Finished.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.plaf.basic.BasicComboBoxUI.setPopupVisible(Unknown Source)
        at javax.swing.plaf.basic.BasicComboBoxUI.uninstallUI(Unknown Source)
        at com.sun.java.swing.plaf.windows.WindowsComboBoxUI.uninstallUI(Unknown Source)
        at javax.swing.JComponent.uninstallUIAndProperties(Unknown Source)
        at javax.swing.JComponent.setUI(Unknown Source)
        at javax.swing.JComboBox.setUI(Unknown Source)
        at javax.swing.JComboBox.updateUI(Unknown Source)
        at nomanssave.ch.a(Unknown Source)
        at nomanssave.aO.a(Unknown Source)
        at nomanssave.Application.j(Unknown Source)
        at nomanssave.Application.h(Unknown Source)
        at nomanssave.Application.q(Unknown Source)
        at nomanssave.T.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Setting units: 300000000

**Comment by 222Stokes** [comment]
I am also having this issue. I get a similar crash report to DavidAlt. All tabs except file, main, and exosuit are greyed out.
Loading slots: C:\Users\stoke\AppData\Roaming\HelloGames\NMS\st_76561198117802926
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
[STDERR] 	at nomanssave.ci.getSize(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.getSelectedIndex(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup.configureList(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup.<init>(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboBoxUI.createPopup(Unknown Source)
[STDERR] 	at com.sun.java.swing.plaf.windows.WindowsComboBoxUI.createPopup(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboBoxUI.installUI(Unknown Source)
[STDERR] 	at com.sun.java.swing.plaf.windows.WindowsComboBoxUI.installUI(Unknown Source)
[STDERR] 	at javax.swing.JComponent.setUI(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setUI(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.updateUI(Unknown Source)
[STDERR] 	at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
[STDERR] 	at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
[STDERR] 	at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
[STDERR] 	at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
[STDERR] 	at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
[STDERR] 	at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
[STDERR] 	at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
[STDERR] 	at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
[STDERR] 	at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
[STDERR] 	at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
[STDERR] 	at javax.swing.SwingUtilities.updateComponentTreeUI0(Unknown Source)
[STDERR] 	at javax.swing.SwingUtilities.updateComponentTreeUI(Unknown Source)
[STDERR] 	at com.sun.java.swing.plaf.windows.DesktopProperty.updateWindowUI(Unknown Source)
[STDERR] 	at com.sun.java.swing.plaf.windows.DesktopProperty.updateAllUIs(Unknown Source)
[STDERR] 	at com.sun.java.swing.plaf.windows.DesktopProperty.access$000(Unknown Source)
[STDERR] 	at com.sun.java.swing.plaf.windows.DesktopProperty$1.run(Unknown Source)
[STDERR] 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
[STDERR] 	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
[STDERR] 	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.awt.WaitDispatchSupport.enter(Unknown Source)
[STDERR] 	at java.awt.Dialog.show(Unknown Source)
[STDERR] 	at javax.swing.JFileChooser.showDialog(Unknown Source)
[STDERR] 	at javax.swing.JFileChooser.showOpenDialog(Unknown Source)
[STDERR] 	at nomanssave.Application.h(Unknown Source)
[STDERR] 	at nomanssave.Application.q(Unknown Source)
[STDERR] 	at nomanssave.C.actionPerformed(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[STDERR] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[STDERR] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton.doClick(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.Component.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.Component.processEvent(Unknown Source)
[STDERR] 	at java.awt.Container.processEvent(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)
[DEBUG] Save Path: C:\Users\stoke\AppData\Roaming\HelloGames\NMS\st_76561198117802926
[INFO] Loading saves for Slot 1...
[INFO] Reading save file...
[INFO] Slot: Slot 1 - SURVIVAL
[INFO] Filename: save.hg
[INFO] Parsing JSON...
[INFO] using name mappings: NMS 1.76
[INFO] Finished.
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
[STDERR] 	at javax.swing.plaf.basic.BasicComboBoxUI.setPopupVisible(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboBoxUI.uninstallUI(Unknown Source)
[STDERR] 	at com.sun.java.swing.plaf.windows.WindowsComboBoxUI.uninstallUI(Unknown Source)
[STDERR] 	at javax.swing.JComponent.uninstallUIAndProperties(Unknown Source)
[STDERR] 	at javax.swing.JComponent.setUI(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setUI(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.updateUI(Unknown Source)
[STDERR] 	at nomanssave.ch.a(Unknown Source)
[STDERR] 	at nomanssave.aO.a(Unknown Source)
[STDERR] 	at nomanssave.Application.j(Unknown Source)
[STDERR] 	at nomanssave.Application.h(Unknown Source)
[STDERR] 	at nomanssave.Application.q(Unknown Source)
[STDERR] 	at nomanssave.C.actionPerformed(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[STDERR] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[STDERR] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[STDERR] 	at javax.swing.AbstractButton.doClick(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.Component.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.Component.processEvent(Unknown Source)
[STDERR] 	at java.awt.Container.processEvent(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Kowalski-ESP** [comment]
So I had this same issue, and I fixed it by using 32 bit java instead of the 64 bit version.

**Comment by SOELexicon** [comment]
also having the same issue. doesn't matter if  i use 32 bit java or 64

**Comment by DarkRavenXL** [comment]
Same issue I'm having.  I have 32bit and 64bit installed besides selecting "program files x86" for 32bit how do you verify?  And is there any other solutions?

**Comment by YammYcoding** [comment]
same here. Can open with the NEXT version, but not with the BEYOND one. If I edit with the previous version would it brake anything ?

**Comment by DarkRavenXL** [comment]
I would make a backup of your save and try....

**Comment by goatfungus** [comment]
This issue should now be fixed (as of version 1.6.3).
