### ISSUE TITLE
JSON Editor out of memory error

### ISSUE THREAD

**Issue by temp-999** [goatfungus/NMSSaveEditor#183]
Thank you for updating your app!

Started up the app. Selected Edit Raw JSON. Did a Search. Was not sure about capitalization, so I unchecked  Case Sensitive and got this:

**Initializing environment...
Starting Editor...
Loading saves for Slot 1...
Reading save file...
  Slot: Slot 1 - NORMAL
  Filename: save.hg
Parsing JSON...
  using name mappings: NMS 2.0
  WARNING: name mapping not found: BpT
  WARNING: name mapping not found: J=S
  WARNING: name mapping not found: vyN
  WARNING: name mapping not found: Bur
Finished.
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
        at java.lang.String.toUpperCase(Unknown Source)
        at java.lang.String.toUpperCase(Unknown Source)
        at nomanssave.cC.a(Unknown Source)
        at nomanssave.bf.actionPerformed(Unknown Source)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)**

Note: Works fine is Case Sensitive is checked and text string is properly uppercase/lowercase.

**Comment by temp-999** [comment]
Received the answer from a hard working NMS forum member.

I had installed the 32-bit version of Java instead of the 64-bit. Brought down the right version, got rid of the old and can now work in the JSON Editor.
