### ISSUE TITLE
Out of Memory Error when saving edited JSON

### ISSUE THREAD

**Issue by lofblad** [goatfungus/NMSSaveEditor#218]
I edited a line in the raw json editor, and when I clicked "Save", I got this:

Initializing environment...
Starting Editor...
Loading saves for Slot 1...
Reading save file...
  Slot: Slot 1 - NORMAL
  Filename: save.hg
Parsing JSON...
  using name mappings: NMS 2.0
  WARNING: name mapping not found: KLP
  WARNING: name mapping not found: fJB
  WARNING: name mapping not found: D9@
  WARNING: name mapping not found: rIR
Finished.
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
        at java.lang.AbstractStringBuilder.append(Unknown Source)
        at java.lang.StringBuffer.append(Unknown Source)
        at nomanssave.cD.q(Unknown Source)
        at nomanssave.cD.s(Unknown Source)
        at nomanssave.cM.setText(Unknown Source)
        at nomanssave.cJ.windowClosing(Unknown Source)
        at java.awt.Window.processWindowEvent(Unknown Source)
        at javax.swing.JDialog.processWindowEvent(Unknown Source)
        at java.awt.Window.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)

**Comment by temp-999** [comment]
Looks like the problem that I had:

https://github.com/goatfungus/NMSSaveEditor/issues/183

**Comment by lofblad** [comment]
> Looks like the problem that I had:
> 
> #183

This was exactly it! Thank you so much!
