### ISSUE TITLE
Major Crash

### ISSUE THREAD

**Issue by ukmerlin** [goatfungus/NMSSaveEditor#222]
So I used a base teleporter to another area and saved stopped the game. Brought the game into NMSE, everything seemed ok. But when I expanded and tried to look at a base it went unresponsive with this in the viewer. Save game attached. Also, there were suddenly about 12 more bases than I actually have showing up.

[save.zip](https://github.com/goatfungus/NMSSaveEditor/files/3721079/save.zip)

  using name mappings: NMS 2.0
Finished.
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
        at javax.swing.text.GapContent.getPositionsInRange(Unknown Source)
        at javax.swing.text.GapContent$RemoveUndo.<init>(Unknown Source)
        at javax.swing.text.GapContent.remove(Unknown Source)
        at javax.swing.text.AbstractDocument.handleRemove(Unknown Source)
        at javax.swing.text.AbstractDocument.remove(Unknown Source)
        at javax.swing.text.AbstractDocument.replace(Unknown Source)
        at javax.swing.text.JTextComponent.setText(Unknown Source)
        at nomanssave.cD.valueChanged(Unknown Source)
        at javax.swing.JTree.fireValueChanged(Unknown Source)
        at javax.swing.JTree$TreeSelectionRedirector.valueChanged(Unknown Source)
        at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(Unknown Source)
        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(Unknown Source)
        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(Unknown Source)
        at javax.swing.JTree.setSelectionPath(Unknown Source)
        at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(Unknown Source)
        at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(Unknown Source)
        at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)

**Comment by ukmerlin** [comment]
Tried pushing on with it by portalling back and seeing how everything was. It worked "further" and twith the right number of bases but when I got to the save stage got this;

Formatting JSON...
  using name mappings: NMS 2.0
Creating backup...
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.lang.StringCoding.safeTrim(Unknown Source)
        at java.lang.StringCoding.access$100(Unknown Source)
        at java.lang.StringCoding$StringDecoder.decode(Unknown Source)
        at java.lang.StringCoding.decode(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at nomanssave.storage.b.c(Unknown Source)
        at nomanssave.storage.b.d(Unknown Source)
        at nomanssave.storage.b.a(Unknown Source)
        at nomanssave.storage.b.a(Unknown Source)
        at nomanssave.storage.m.g(Unknown Source)
        at nomanssave.Application.l(Unknown Source)
        at nomanssave.Application.j(Unknown Source)
        at nomanssave.y.actionPerformed(Unknown Source)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
Formatting JSON...
  using name mappings: NMS 2.0
Creating backup...
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

**Comment by temp-999** [comment]
Looks like the problem that I had:

#183

**Comment by ukmerlin** [comment]
OMG thank you!!
that was the problem, saved a day one save........ :)
