### ISSUE TITLE
Editor can't save edits, Exception occurred

### ISSUE THREAD

**Issue by RyuujiTa** [goatfungus/NMSSaveEditor#257]
At first I could edit my save game, but after a few days of using the editor I can no longer save the edits I do to the file.

`Initializing environment...
Starting Editor...
Loading saves for Slot 1...
Reading save file...
  Slot: Slot 1 - NORMAL - Mär 3, 21:47
  Filename: save2.hg
Parsing JSON...
  using name mappings: NMS 2.31
Finished.
Formatting JSON...
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at nomanssave.util.h.getValue(Unknown Source)
        at nomanssave.util.h.al(Unknown Source)
        at nomanssave.Application.p(Unknown Source)
        at nomanssave.Application.q(Unknown Source)
        at nomanssave.Application.j(Unknown Source)
        at nomanssave.D.actionPerformed(Unknown Source)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by Ahdobo** [comment]
I'm having the same problem. Did you find a fix?

**Comment by RyuujiTa** [comment]
No, regrettably not. I reinstalled the editor and the game, but I got the same error

**Comment by Devilin-Pixy** [comment]
I could be wrong, but having decompiled the jar, trying to trace the error events from your log above, it appears to be related to an issue with the Multitool(s).

Did you just get an extra multitool, or have you made edits to a multitool's inventory or something related?

Also curious to know if the same issue exists with a new save or other saves?

Note: I won't be able to solve the issue, just trying to help. Hopefully goatfungus can have a good look at it and pinpoint the culprit.

**Comment by RyuujiTa** [comment]
Yes I did buy a new multi tool and used the editor to move my upgrades from the old one to the new one. Could this have caused it?

**Comment by goatfungus** [comment]
This issue was fixed in a recent update.
