### ISSUE TITLE
Cant save my base updates

### ISSUE THREAD

**Issue by Miangoco** [goatfungus/NMSSaveEditor#337]
i use blender to edit my base and all was good at the begining but now it doesnt save,

 and using the batch file it says this

Formatting JSON...
  using name mappings: NMS 3.0
Creating backup...
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.lang.StringCoding.safeTrim(Unknown Source)
        at java.lang.StringCoding.access$100(Unknown Source)
        at java.lang.StringCoding$StringDecoder.decode(Unknown Source)
        at java.lang.StringCoding.decode(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at nomanssave.storage.b.c(Unknown Source)
        at nomanssave.storage.b.d(Unknown Source)
        at nomanssave.storage.b.a(Unknown Source)
        at nomanssave.storage.b.a(Unknown Source)
        at nomanssave.storage.m.g(Unknown Source)
        at nomanssave.Application.q(Unknown Source)
        at nomanssave.Application.j(Unknown Source)
        at nomanssave.D.actionPerformed(Unknown Source)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)

**Comment by Novoca1n3** [comment]
This happens when you visit a system that has a lot of user bases and you're using the x86 version of JAVA. Install the x64 version of JAVA and uninstall x86

**Comment by Miangoco** [comment]
> This happens when you visit a system that has a lot of user bases and you're using the x86 version of JAVA. Install the x64 version of JAVA and uninstall x86

Thank u that was it, i only had to save in another empty system :P, and im now checking the java x86 issue
