### ISSUE TITLE
How to solve my problem in this archive？

### ISSUE THREAD

**Issue by forestbat** [goatfungus/NMSSaveEditor#364]
Yesterday I want to complete my expedition mode more quickly，so I changed “F2P” field in my archive from 4641 to 7201，and as a result，the archive has been broken and even if I change F2P to 4641 the game still can't read this archieve.
Now every data is still saved in this archieve，but I only can play it take a start from the head，how to solve this？It's an 800 hours' archieve，I don‘t want to lose it.
This is the file，and when I try to open it with NMSSaveEditor，it occurs mistake information like this：

> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at nomanssave.aJ.a(Unknown Source)
        at nomanssave.Application.p(Unknown Source)
        at nomanssave.Application.n(Unknown Source)
        at nomanssave.Application.r(Unknown Source)
        at nomanssave.ac.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

#362 I think this is a similar problem.

**Comment by forestbat** [comment]
https://drive.google.com/file/d/1WgtUZfZABUkdaADEzxa5ssMfGrQTE0_j/view?usp=sharing
https://drive.google.com/file/d/1uxhsqiicY1iKHSxEduihuTkhp13U0SJX/view?usp=sharing
They are auto and manual saves of this archive.

**Comment by goatfungus** [comment]
7201 is the custom game mode for Expeditions which starts off with some special states and events. I wouldn't try to swap versions from an old "normal" save to the new Expedition format unless you really know what you're doing, as you'll likely have a broken game. I would change it back if I were you (reload an older backup and re-save the file).

**Comment by forestbat** [comment]
It's a pity that I don't have older backup and even if I change it back to 4641 it's still broken,I have said.
Now I update my NMS version and use 1.7.5 to check this archive but I still can't recover my game progress.
I heard that change 4641 to 7201 can use your archive which has many resources to complete Expeditions mode faster and that someone has used this method successfully，however my save has broken，this result makes me surprise.
So do you have method to recover my archive？All data are still saved in this save，I’d be grateful if you could help me.
And this is error report：
`ERROR: Could not load save file: save.hg
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at nomanssave.ao.a(Unknown Source)
        at nomanssave.Application.p(Unknown Source)
        at nomanssave.Application.o(Unknown Source)
        at nomanssave.Application.n(Unknown Source)
        at nomanssave.C.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`
