### ISSUE TITLE
AWT-EventQueue-0

### ISSUE THREAD

**Issue by Ripjawws** [goatfungus/NMSSaveEditor#387]
There have been various issues with this and i cant seem to find an answer anywhere.
Initializing environment...
Starting Editor...
Loading saves for Slot 1...
Reading save file...
  Slot: Slot 1 - NORMAL - May 23, 14:28
  Filename: save.hg
ERROR: Could not load save file: save.hg
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at nomanssave.ao.a(Unknown Source)
        at nomanssave.Application.p(Unknown Source)
        at nomanssave.Application.o(Unknown Source)
        at nomanssave.Application.n(Unknown Source)
        at nomanssave.C.setSelectedItem(Unknown Source)

**Comment by goatfungus** [comment]
This should be fixed already, but if you still have this issue, please send me your save files and I'll check.
