### ISSUE TITLE
Edit Raw JSON crashes from one save

### ISSUE THREAD

**Issue by Nimarus84** [goatfungus/NMSSaveEditor#55]
This only happens with my current game save. I have no idea why. When I click on "Edit Raw JSON", the editor freezes and eventually starts working again, but without opening the JSON to edit. The black screen shows this:

> Latest version: "1.5.9"
Current version: "1.5.9"
Loading saves for save 2...
Reading save file...
  Path: C:\Users\amart\AppData\Roaming\HelloGames\NMS\st_76561198371500615
  Slot: Slot 2 - NORMAL
  Filename: save3.hg
Parsing JSON...
Finished.
Reading save file...
  Path: C:\Users\amart\AppData\Roaming\HelloGames\NMS\st_76561198371500615
  Slot: Slot 2 - NORMAL
  Filename: save4.hg
Parsing JSON...
Finished.
Reading save file...
  Path: C:\Users\amart\AppData\Roaming\HelloGames\NMS\st_76561198371500615
  Slot: Slot 2 - NORMAL
  Filename: save3.hg
Parsing JSON...
Finished.
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
        at java.io.BufferedInputStream.<init>(Unknown Source)
        at java.io.BufferedInputStream.<init>(Unknown Source)
        at sun.util.locale.provider.RuleBasedBreakIterator$1.run(Unknown Source)
        at sun.util.locale.provider.RuleBasedBreakIterator$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.util.locale.provider.RuleBasedBreakIterator.readFile(Unknown Source)
        at sun.util.locale.provider.RuleBasedBreakIterator.readTables(Unknown Source)
        at sun.util.locale.provider.RuleBasedBreakIterator.<init>(Unknown Source)
        at sun.util.locale.provider.BreakIteratorProviderImpl.getBreakInstance(Unknown Source)
        at sun.util.locale.provider.BreakIteratorProviderImpl.getLineInstance(Unknown Source)
        at java.text.BreakIterator.createBreakInstance(Unknown Source)
        at java.text.BreakIterator.createBreakInstance(Unknown Source)
        at java.text.BreakIterator.getBreakInstance(Unknown Source)
        at java.text.BreakIterator.getLineInstance(Unknown Source)
        at javax.swing.text.TextLayoutStrategy.sync(Unknown Source)
        at javax.swing.text.TextLayoutStrategy.insertUpdate(Unknown Source)
        at javax.swing.text.FlowView.loadChildren(Unknown Source)
        at javax.swing.text.CompositeView.setParent(Unknown Source)
        at javax.swing.text.FlowView.setParent(Unknown Source)
        at javax.swing.plaf.basic.BasicTextAreaUI$PlainParagraph.setParent(Unknown Source)
        at javax.swing.text.CompositeView.replace(Unknown Source)
        at javax.swing.text.BoxView.replace(Unknown Source)
        at javax.swing.text.CompositeView.loadChildren(Unknown Source)
        at javax.swing.text.CompositeView.setParent(Unknown Source)
        at javax.swing.plaf.basic.BasicTextUI$RootView.setView(Unknown Source)
        at javax.swing.plaf.basic.BasicTextUI.setView(Unknown Source)
        at javax.swing.plaf.basic.BasicTextUI.modelChanged(Unknown Source)
        at javax.swing.plaf.basic.BasicTextUI$UpdateHandler.insertUpdate(Unknown Source)
        at javax.swing.text.AbstractDocument.fireInsertUpdate(Unknown Source)
        at javax.swing.text.AbstractDocument.handleInsertString(Unknown Source)
        at javax.swing.text.AbstractDocument.insertString(Unknown Source)
        at javax.swing.text.PlainDocument.insertString(Unknown Source)

> 
I hope this helps.

**Comment by goatfungus** [comment]
How much RAM do you have on your machine? Your save file must be quite large as well.
I will be releasing a few extra runtime options in the next release that should hopefully solve this sort of memory issue.

**Comment by goatfungus** [comment]
I have added some new executables for those who don't have much RAM available... try running the ones with the -4G suffix.
