### ISSUE TITLE
Unable to edit / Change settings

### ISSUE THREAD

**Issue by RealSourceOfficial** [goatfungus/NMSSaveEditor#572]
Editor is not saving (log [here](https://github.com/goatfungus/NMSSaveEditor/files/8699649/NMSSaveEditor.log))

Actual Error (for convenience): 
```
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 6
[STDERR] 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[STDERR] 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[STDERR] 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[STDERR] 	at java.base/java.util.Objects.checkIndex(Objects.java:359)
[STDERR] 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
[STDERR] 	at nomanssave.util.f.getValue(Unknown Source)
[STDERR] 	at nomanssave.util.f.as(Unknown Source)
[STDERR] 	at nomanssave.Application.t(Unknown Source)
[STDERR] 	at nomanssave.Application.w(Unknown Source)
[STDERR] 	at nomanssave.Application.c(Unknown Source)
[STDERR] 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
[STDERR] 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
[STDERR] 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
[STDERR] 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[STDERR] 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
[STDERR] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
[STDERR] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
[STDERR] 	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
[STDERR] 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
[STDERR] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
[STDERR] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
[STDERR] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
[STDERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
[STDERR] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
[STDERR] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
[STDERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by Astiah** [comment]
I'm having exact same error with up-to-date Java, no idea what's going wrong...
