### ISSUE TITLE
Leviathan freight tab not working // Help attached

### ISSUE THREAD

**Issue by MrMfG** [goatfungus/NMSSaveEditor#579]
when you pick up leviathan frigate you cant edit or dupe them anymore.
here is the stuff out the json for manual add so save and to editor:
{
		"ResourceSeed":[
			true,
			"0x1"
		],
		"HomeSystemSeed":[
			true,
			"0x1"
		],
		"TimeOfLastIncomeCollection":1653670626,
		"CustomName":"The Leviathan",
		"FrigateClass":{
			"FrigateClass":"DeepSpace"
		},
		"Race":{
			"AlienRace":"Warriors"
		},
		"TotalNumberOfExpeditions":34,
		"TotalNumberOfSuccessfulEvents":447,
		"TotalNumberOfFailedEvents":29,
		"NumberOfTimesDamaged":1,
		"TraitIDs":[
			"^DEEPSPACE_1",
			"^DEEPSPACE_2",
			"^DEEPSPACE_3",
			"^DEEPSPACE_4",
			"^DEEPSPACE_5"
		],
		"Stats":[
			15,
			23,
			6,
			22,
			8,
			9,
			0,
			0,
			0,
			1,
			0
		],
		"RepairsMade":0,
		"DamageTaken":0
	},

**Comment by KarmaIsLame** [comment]
same here, frigate page won't load properly.

**Comment by Mike-Blackwell** [comment]
I can second that the Frigate page is over writing its self making it break.. 

@[MrMfG](https://github.com/MrMfG) thanxs for the cut/paste, you need to fix it the last like should not have a common at the end, otherwise it works great

**Comment by rasa2k** [comment]
Same problem here:
`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at nomanssave.bO.getValueAt(Unknown Source)
        at javax.swing.JTable.getValueAt(Unknown Source)
        at javax.swing.JTable.prepareRenderer(Unknown Source)
        at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
        at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
        at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
        at javax.swing.plaf.ComponentUI.update(Unknown Source)
        at javax.swing.JComponent.paintComponent(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JViewport.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintToOffscreen(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
        at javax.swing.RepaintManager.paint(Unknown Source)
        at javax.swing.JComponent._paintImmediately(Unknown Source)
        at javax.swing.JComponent.paintImmediately(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by goatfungus** [comment]
Thanks for the info, I think I have got this working now. Let me know how it goes.
