### ISSUE TITLE
New Organic Frigate - Editor Issue

### ISSUE THREAD

**Issue by webrunnerjrh** [goatfungus/NMSSaveEditor#615]
Picked up a new Organic Frigate introduced with Endurance update. Today, can't open Frigate tab in Editor. Frigate tab works fine on saves prior to getting an Organic Frigate.

Following is error log:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at nomanssave.bO.getValueAt(Unknown Source)
at javax.swing.JTable.getValueAt(Unknown Source)
at javax.swing.JTable.prepareRenderer(Unknown Source)
at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
at javax.swing.plaf.ComponentUI.update(Unknown Source)
at javax.swing.JComponent.paintComponent(Unknown Source)
at javax.swing.JComponent.paint(Unknown Source)
at javax.swing.JComponent.paintChildren(Unknown Source)
at javax.swing.JComponent.paint(Unknown Source)
at javax.swing.JViewport.paint(Unknown Source)
at javax.swing.JComponent.paintChildren(Unknown Source)
at javax.swing.JComponent.paint(Unknown Source)
at javax.swing.JComponent.paintChildren(Unknown Source)
at javax.swing.JComponent.paint(Unknown Source)
at javax.swing.JComponent.paintChildren(Unknown Source)
at javax.swing.JComponent.paint(Unknown Source)
at javax.swing.JComponent.paintChildren(Unknown Source)
at javax.swing.JComponent.paint(Unknown Source)
at javax.swing.JComponent.paintChildren(Unknown Source)
at javax.swing.JComponent.paint(Unknown Source)
at javax.swing.JComponent.paintToOffscreen(Unknown Source)
at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
at javax.swing.RepaintManager.paint(Unknown Source)
at javax.swing.JComponent._paintImmediately(Unknown Source)
at javax.swing.JComponent.paintImmediately(Unknown Source)
at javax.swing.RepaintManager$4.run(Unknown Source)
at javax.swing.RepaintManager$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
at javax.swing.RepaintManager.access$1200(Unknown Source)
at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
at java.awt.event.InvocationEvent.dispatch(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)

'preciate ya.

WebR

**Comment by MadBlue2112** [comment]
I'm getting the same message. I don't know if this may have something to do with it, but my organic frigate had been sent out on an expedition and came back "critically damaged" and I couldn't seem to repair it in-game through feeding it.  Apparently this is due to a bug, so it may have something to do with the error message if the error message doesn't appear with undamaged organic frigates.

**Comment by IndorilKai** [comment]
Hi, I think the error is that the "FrigateClass" of Organic Frigates are categorized as "DeepSpaceCommon" in the game but the NMSSE has tagged it as "Living". That's why it can't display the frigate type.

**Comment by Kayla** [comment]
I can confirm that changing the class from nothing to Living in the editor causes the ship to disappear in game. You cannot fix it normally since you can't choose the unrecognized value, so it ends up breaking your ships. I would just keep the ships as broken for now, and if you need to do anything in the frigate menu in NMSSE you can hold tab to select the first Frigate and up and down arrows scroll through the list.

**Comment by IndorilKai** [comment]
Hi, don't change your Organic frigates to "Living" since the blanks/nothing is already the correct value. 

If you want to change your frigates to Living Ships, you can edit the Raw JSON and change the original class to "DeepSpaceCommon" instead of "Living".

**Comment by goatfungus** [comment]
Thanks for the detailed information on this issue. It should be all working now.

Enjoy!
