### ISSUE TITLE
Errors in console on loading save

### ISSUE THREAD

**Issue by ChaosPaladin** [goatfungus/NMSSaveEditor#627]
```
[INFO] Reading account data...
[INFO] using name mappings: NMS 3.94 (account)
[DEBUG] Mem Usage: 537/4295 MB
[DEBUG] Latest version: "1.10.6"
[DEBUG] Current version: "1.10.6"
[INFO] Loading saves for Slot 3...
[INFO] Reading save file...
[INFO] Slot: Slot 3 - NORMAL - Jul. 25, 21:31
[INFO] Filename: save6.hg
[INFO] using name mappings: NMS 3.94 (savegame)
[WARNING] name mapping not found: tIM
[WARNING] name mapping not found: 7:k
[WARNING] name mapping not found: SQw
[WARNING] name mapping not found: Naj
[INFO] Finished.
[INFO] Ship 1 - General slot[3,1] appears to be broken, ignoring
[INFO] Ship 1 - General slot[5,1] appears to be broken, ignoring
[INFO] Ship 1 - General slot[6,1] appears to be broken, ignoring
[INFO] Ship 1 - General slot[1,2] appears to be broken, ignoring
[INFO] Ship 1 - General slot[2,2] appears to be broken, ignoring
[INFO] Ship 1 - General slot[3,2] appears to be broken, ignoring
[INFO] Ship 1 - General slot[5,2] appears to be broken, ignoring
[INFO] Ship 1 - General slot[6,2] appears to be broken, ignoring
[INFO] Ship 1 - General slot[2,3] appears to be broken, ignoring
[INFO] Ship 1 - General slot[5,3] appears to be broken, ignoring
[INFO] Ship 1 - General slot[2,4] appears to be broken, ignoring
[INFO] Ship 1 - General slot[4,4] appears to be broken, ignoring
[INFO] Ship 1 - General slot[5,4] appears to be broken, ignoring
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: No enum constant nomanssave.structures.h.LandJellyfish
[STDERR] 	at java.base/java.lang.Enum.valueOf(Enum.java:240)
[STDERR] 	at nomanssave.structures.h.valueOf(Unknown Source)
[STDERR] 	at nomanssave.structures.g.cc(Unknown Source)
[STDERR] 	at nomanssave.ao.setSelectedItem(Unknown Source)
[STDERR] 	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:579)
[STDERR] 	at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:624)
[STDERR] 	at nomanssave.an.a(Unknown Source)
[STDERR] 	at nomanssave.Application.s(Unknown Source)
[STDERR] 	at nomanssave.Application.e(Unknown Source)
[STDERR] 	at nomanssave.Application.a(Unknown Source)
[STDERR] 	at nomanssave.I.setSelectedItem(Unknown Source)
[STDERR] 	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:579)
[STDERR] 	at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:624)
[STDERR] 	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:907)
[STDERR] 	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
[STDERR] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
[STDERR] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
[STDERR] 	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:551)
[STDERR] 	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
[STDERR] 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
[STDERR] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
[STDERR] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
[STDERR] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
[STDERR] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
[STDERR] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[STDERR] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
[STDERR] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by Devilin-Pixy** [comment]
Looks like a pet may be causing an issue. Any modded pets perhaps?

**Comment by goatfungus** [comment]
See #624
