### ISSUE TITLE
Error loading save

### ISSUE THREAD

**Issue by AnimeshnikMC** [goatfungus/NMSSaveEditor#661]
I suggest a log with an error

> [DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_341
[DEBUG] Working Dir: C:\Users\Prototype\Downloads\NMSSaveEditor
[INFO] Starting Editor...
[INFO] Reading metadata for accountdata.hg
[INFO] Reading metadata for save.hg
[INFO] Reading metadata for save2.hg
[DEBUG] Storage: Steam
[DEBUG] Save Path: C:\Users\Prototype\AppData\Roaming\HelloGames\NMS\st_76561198152875427
[INFO] Reading account data...
[DEBUG] Mapping not available: bGK
[DEBUG] Mapping not available: ORx
[DEBUG] Mapping not available: WA4
[DEBUG] Mapping not available: rri
[DEBUG] Mapping not available: tIM
[DEBUG] Mapping not available: e4G
[INFO] using name mappings: NMS 4.0 (account)
[DEBUG] Mem Usage: 129/3818 MB
[DEBUG] Latest version: "1.11.0"
[DEBUG] Current version: "1.11.0"
[INFO] Loading saves for Slot 1...
[INFO] Reading save file...
[INFO] Slot: Slot 1 - [EMPTY]
[INFO] Filename: save2.hg
[INFO] using name mappings: NMS 4.0 (savegame)
[INFO] Finished.
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
[STDERR] 	at nomanssave.structures.q.<init>(Unknown Source)
[STDERR] 	at nomanssave.structures.w.<init>(Unknown Source)
[STDERR] 	at nomanssave.structures.w.o(Unknown Source)
[STDERR] 	at nomanssave.Application.s(Unknown Source)
[STDERR] 	at nomanssave.Application.e(Unknown Source)
[STDERR] 	at nomanssave.Application.a(Unknown Source)
[STDERR] 	at nomanssave.I.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.Component.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.Component.processEvent(Unknown Source)
[STDERR] 	at java.awt.Container.processEvent(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)
[INFO] Reading save file...
[INFO] Slot: Slot 1 - [EMPTY]
[INFO] Filename: save.hg
[INFO] using name mappings: NMS 4.0 (savegame)
[INFO] Finished.
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
[STDERR] 	at nomanssave.structures.q.<init>(Unknown Source)
[STDERR] 	at nomanssave.structures.w.<init>(Unknown Source)
[STDERR] 	at nomanssave.structures.w.o(Unknown Source)
[STDERR] 	at nomanssave.Application.s(Unknown Source)
[STDERR] 	at nomanssave.Application.f(Unknown Source)
[STDERR] 	at nomanssave.Application.b(Unknown Source)
[STDERR] 	at nomanssave.J.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.Component.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.Component.processEvent(Unknown Source)
[STDERR] 	at java.awt.Container.processEvent(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by AndyGFX** [comment]
Another similar error:

```
Initializing environment...
Starting Editor...
Reading metadata for accountdata.hg
Reading metadata for save3.hg
Reading metadata for save4.hg
Reading account data...
  using name mappings: NMS 4.0 (account)
Loading saves for Slot 2...
Reading save file...
  Slot: Slot 2 - [EMPTY]
  Filename: save4.hg
  using name mappings: NMS 4.0 (savegame)
  WARNING: name mapping not found: ?6B
Finished.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "nomanssave.storage.c.ordinal()" because the return value of "nomanssave.Application.L()" is null
        at nomanssave.structures.q.<init>(Unknown Source)
        at nomanssave.structures.w.<init>(Unknown Source)
        at nomanssave.structures.w.o(Unknown Source)
        at nomanssave.Application.s(Unknown Source)
        at nomanssave.Application.e(Unknown Source)
        at nomanssave.Application.a(Unknown Source)
        at nomanssave.I.setSelectedItem(Unknown Source)
        at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:609)
        at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:654)
        at java.desktop/javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:946)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:551)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by MrDead115** [comment]
### same sort of thing cant load my main save up 

----------------------------------------------------


Initializing environment...
Starting Editor...
Reading metadata for accountdata.hg
Reading metadata for save3.hg
Reading metadata for save4.hg
Reading account data...
  using name mappings: NMS 4.0 (account)
  using name mappings: NMS 4.0 (account)
Loading saves for Slot 2...
Reading save file...
  Slot: Slot 2 - [EMPTY]
  Filename: save3.hg
  using name mappings: NMS 4.0 (savegame)
Finished.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at nomanssave.structures.q.<init>(Unknown Source)
        at nomanssave.structures.w.<init>(Unknown Source)
        at nomanssave.structures.w.o(Unknown Source)
        at nomanssave.Application.s(Unknown Source)
        at nomanssave.Application.e(Unknown Source)
        at nomanssave.Application.a(Unknown Source)
        at nomanssave.I.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by donmitson** [comment]
**Cant load save**

[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_341
[DEBUG] Working Dir: C:\Users\dkara\Desktop\NMSSaveEditor-master
[INFO] Starting Editor...
[INFO] Reading metadata for accountdata.hg
[INFO] Reading metadata for save.hg
[INFO] Reading metadata for save2.hg
[INFO] Reading metadata for save3.hg
[INFO] Reading metadata for save4.hg
[DEBUG] Storage: Steam
[DEBUG] Save Path: C:\Users\dkara\AppData\Roaming\HelloGames\NMS\st_76561198081989980
[INFO] Reading account data...
[DEBUG] Mapping not available: bGK
[DEBUG] Mapping not available: ORx
[DEBUG] Mapping not available: WA4
[DEBUG] Mapping not available: rri
[DEBUG] Mapping not available: tIM
[DEBUG] Mapping not available: e4G
[INFO] using name mappings: NMS 4.0 (account)
[DEBUG] Mem Usage: 257/3808 MB
[DEBUG] Latest version: "1.11.0"
[DEBUG] Current version: "1.11.0"
[DEBUG] Storage: Steam
[DEBUG] Save Path: C:\Users\dkara\AppData\Roaming\HelloGames\NMS\st_76561198081989980
[INFO] using name mappings: NMS 4.0 (account)
[INFO] Loading saves for Slot 2...
[INFO] Reading save file...
[INFO] Slot: Slot 2 - [EMPTY]
[INFO] Filename: save4.hg
[INFO] using name mappings: NMS 4.0 (savegame)
[INFO] Finished.
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
[STDERR] 	at nomanssave.structures.q.<init>(Unknown Source)
[STDERR] 	at nomanssave.structures.w.<init>(Unknown Source)
[STDERR] 	at nomanssave.structures.w.o(Unknown Source)
[STDERR] 	at nomanssave.Application.s(Unknown Source)
[STDERR] 	at nomanssave.Application.e(Unknown Source)
[STDERR] 	at nomanssave.Application.a(Unknown Source)
[STDERR] 	at nomanssave.I.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
[STDERR] 	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
[STDERR] 	at java.awt.Component.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[STDERR] 	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.Component.processEvent(Unknown Source)
[STDERR] 	at java.awt.Container.processEvent(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[STDERR] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.Component.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[STDERR] 	at java.awt.EventQueue.access$500(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$3.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.awt.EventQueue$4.run(Unknown Source)
[STDERR] 	at java.security.AccessController.doPrivileged(Native Method)
[STDERR] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[STDERR] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[STDERR] 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by ShikaRoddy** [comment]
Initializing environment...
Starting Editor...
Reading metadata for accountdata.hg
Reading metadata for save.hg
Reading metadata for save2.hg
Reading account data...
  using name mappings: NMS 4.0 (account)
WARNING: Error reading account data
Loading saves for Slot 1...
Reading save file...
  Slot: Slot 1 - [EMPTY]
  Filename: save2.hg
  using name mappings: NMS 4.0 (savegame)
  WARNING: name mapping not found: SQw
  WARNING: name mapping not found: Naj
Finished.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at nomanssave.structures.q.<init>(Unknown Source)
        at nomanssave.structures.w.<init>(Unknown Source)
        at nomanssave.structures.w.o(Unknown Source)
        at nomanssave.Application.s(Unknown Source)
        at nomanssave.Application.e(Unknown Source)
        at nomanssave.Application.a(Unknown Source)
        at nomanssave.I.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by goatfungus** [comment]
Custom and Relaxed game modes were added in 4.0... I haven't yet bolted them into the editor... coming soon...
