### ISSUE TITLE
NullPointerException Discovery Tab

### ISSUE THREAD

**Issue by Augestflex** [goatfungus/NMSSaveEditor#667]
Initializing environment...
Starting Editor...
Loading storage: C:\Users\ThePath\AppData\Roaming\HelloGames\NMS\st_76561198027825388
Reading metadata for accountdata.hg
Reading metadata for save.hg
  Version: 1
  TotalPlayTime: 280:33
Reading metadata for save2.hg
  Version: 1
  TotalPlayTime: 280:34
Reading metadata for save3.hg
  Version: 1
  TotalPlayTime: 47:58
Reading metadata for save4.hg
  Version: 1
  TotalPlayTime: 47:58
Reading metadata for save5.hg
  Version: 1
  TotalPlayTime: 25:17
Reading metadata for save6.hg
  Version: 327686
  TotalPlayTime: 25:13
Reading metadata for save7.hg
  Version: 1
  TotalPlayTime: 14:03
Reading metadata for save8.hg
  Version: 262150
  TotalPlayTime: 13:45
Reading metadata for save9.hg
  Version: 1
  TotalPlayTime: 345:29
Reading metadata for save10.hg
  Version: 1
  TotalPlayTime: 345:26
Reading metadata for save11.hg
  Version: 1
  TotalPlayTime: 17:27
Reading metadata for save12.hg
  Version: 393222
  TotalPlayTime: 17:10
Reading metadata for save13.hg
  Version: 1
  TotalPlayTime: 28:22
Reading metadata for save14.hg
  Version: 1
  TotalPlayTime: 28:22
Reading metadata for save15.hg
  Version: 1
  TotalPlayTime: 23:32
Reading metadata for save16.hg
  Version: 1
  TotalPlayTime: 23:33
Reading metadata for save17.hg
  Version: 5
  TotalPlayTime: 19:38
Reading metadata for save18.hg
  Version: 5
  TotalPlayTime: 7:49
Reading metadata for save19.hg
  Version: 3
  TotalPlayTime: 19:37
Reading metadata for save20.hg
  Version: 720902
  TotalPlayTime: 17:20
Reading metadata for save21.hg
  Version: 786438
  TotalPlayTime: 17:30
Reading metadata for save22.hg
  Version: 1
  TotalPlayTime: 17:34
  using name mappings: NMS 4.0 (account)
Loading saves for Slot 5...
Reading save file...
  Slot: Slot 5 - NORMAL - Jul 29, 11:09
  Filename: save9.hg
  using name mappings: NMS 4.0 (savegame)
  WARNING: name mapping not found: SQw
  WARNING: name mapping not found: Naj
  WARNING: name mapping not found: 4In
  WARNING: name mapping not found: HXT
  WARNING: name mapping not found: UVd
  WARNING: name mapping not found: lFr
  WARNING: name mapping not found: DqZ
  WARNING: name mapping not found: amP
  WARNING: name mapping not found: 0xI
  WARNING: name mapping not found: yID
  WARNING: name mapping not found: WmI
  WARNING: name mapping not found: IsL
  WARNING: name mapping not found: MMA
  WARNING: name mapping not found: AeI
  WARNING: name mapping not found: rER  
Finished.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.sun.java.swing.plaf.windows.WindowsTableHeaderUI$XPDefaultRenderer.paint(Unknown Source)
        at javax.swing.CellRendererPane.paintComponent(Unknown Source)
        at javax.swing.plaf.basic.BasicTableHeaderUI.paintCell(Unknown Source)
        at javax.swing.plaf.basic.BasicTableHeaderUI.paint(Unknown Source)
        at javax.swing.plaf.ComponentUI.update(Unknown Source)
        at javax.swing.JComponent.paintComponent(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JViewport.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintToOffscreen(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
        at javax.swing.RepaintManager.paint(Unknown Source)
        at javax.swing.JComponent._paintImmediately(Unknown Source)
        at javax.swing.JComponent.paintImmediately(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Augestflex** [comment]
It turns out this occurs with both the Account Tab and Discovery Tab.

Are there additional details I can provide that will help?

**Comment by Devilin-Pixy** [comment]
Did you update to the latest version (currently 1.11.2), and this still happens?

**Comment by Augestflex** [comment]
I appreciate the response and I did try again with 1.11.2 and it still occurs. It turns out this happens on both Discovery Tab and Account Tab.

Here is the current stack trace:
Initializing environment...
Starting Editor...
Loading storage: I_REMOVED_THE_PATH
Reading metadata for accountdata.hg
Reading metadata for save.hg
  Version: 1
  TotalPlayTime: 280:33
Reading metadata for save2.hg
  Version: 1
  TotalPlayTime: 280:34
Reading metadata for save3.hg
  Version: 1
  TotalPlayTime: 47:58
Reading metadata for save4.hg
  Version: 1
  TotalPlayTime: 47:58
Reading metadata for save5.hg
  Version: 1
  TotalPlayTime: 25:17
Reading metadata for save6.hg
  Version: 327686
  TotalPlayTime: 25:13
Reading metadata for save7.hg
  Version: 1
  TotalPlayTime: 14:03
Reading metadata for save8.hg
  Version: 262150
  TotalPlayTime: 13:45
Reading metadata for save9.hg
  Version: 1
  TotalPlayTime: 345:29
Reading metadata for save10.hg
  Version: 1
  TotalPlayTime: 345:26
Reading metadata for save11.hg
  Version: 1
  TotalPlayTime: 17:27
Reading metadata for save12.hg
  Version: 393222
  TotalPlayTime: 17:10
Reading metadata for save13.hg
  Version: 1
  TotalPlayTime: 28:22
Reading metadata for save14.hg
  Version: 1
  TotalPlayTime: 28:22
Reading metadata for save15.hg
  Version: 1
  TotalPlayTime: 23:32
Reading metadata for save16.hg
  Version: 1
  TotalPlayTime: 23:33
Reading metadata for save17.hg
  Version: 5
  TotalPlayTime: 19:38
Reading metadata for save18.hg
  Version: 5
  TotalPlayTime: 7:49
Reading metadata for save19.hg
  Version: 3
  TotalPlayTime: 19:37
Reading metadata for save20.hg
  Version: 720902
  TotalPlayTime: 17:20
Reading metadata for save21.hg
  Version: 786438
  TotalPlayTime: 17:30
Reading metadata for save22.hg
  Version: 1
  TotalPlayTime: 17:34
  using name mappings: NMS 4.0 (account)
Loading saves for Slot 5...
Reading save file...
  Slot: Slot 5 - NORMAL - Jul 29, 11:09
  Filename: save9.hg
  using name mappings: NMS 4.0 (savegame)
  WARNING: name mapping not found: SQw
  WARNING: name mapping not found: Naj
Finished.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.sun.java.swing.plaf.windows.WindowsTableHeaderUI$XPDefaultRenderer.paint(Unknown Source)
        at javax.swing.CellRendererPane.paintComponent(Unknown Source)
        at javax.swing.plaf.basic.BasicTableHeaderUI.paintCell(Unknown Source)
        at javax.swing.plaf.basic.BasicTableHeaderUI.paint(Unknown Source)
        at javax.swing.plaf.ComponentUI.update(Unknown Source)
        at javax.swing.JComponent.paintComponent(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JViewport.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintToOffscreen(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
        at javax.swing.RepaintManager.paint(Unknown Source)
        at javax.swing.JComponent._paintImmediately(Unknown Source)
        at javax.swing.JComponent.paintImmediately(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.sun.java.swing.plaf.windows.WindowsTableHeaderUI$XPDefaultRenderer.paint(Unknown Source)
        at javax.swing.CellRendererPane.paintComponent(Unknown Source)
        at javax.swing.plaf.basic.BasicTableHeaderUI.paintCell(Unknown Source)
        at javax.swing.plaf.basic.BasicTableHeaderUI.paint(Unknown Source)
        at javax.swing.plaf.ComponentUI.update(Unknown Source)
        at javax.swing.JComponent.paintComponent(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JViewport.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintToOffscreen(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
        at javax.swing.RepaintManager.paint(Unknown Source)
        at javax.swing.JComponent._paintImmediately(Unknown Source)
        at javax.swing.JComponent.paintImmediately(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Augestflex** [comment]
I appreciate the notes. I have been having this issue so haven't been playing this save. I will update the save. I am on Java 8 64-bit but I installed both just in case.

**Comment by Augestflex** [comment]
After opening and saving in the Waypoint version I receive the same Discovery and Account tab errors preventing me from opening them in NMS. 

The mapping warnings did decrease but unfortunately I still cannot open the **Discovery** or **Account** tabs.

**Comment by goatfungus** [comment]
Should be fixed now.

**Comment by Augestflex** [comment]
AWESOME!!!! Thank you.
