### ISSUE TITLE
Nintendo switch [Invalid Header]

### ISSUE THREAD

**Issue by fennectech** [goatfungus/NMSSaveEditor#696]
`[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_351
[DEBUG] Working Dir: C:\Users\fennectech\Desktop\=EDIT=
[INFO] Starting Editor...
[WARNING] cannot read file metadata: savedata00.hg
[WARNING] java.io.IOException: Invalid header
	at nomanssave.storage.w.<init>(Unknown Source)
	at nomanssave.storage.q.<init>(Unknown Source)
	at nomanssave.storage.p.<init>(Unknown Source)
	at nomanssave.storage.f.a(Unknown Source)
	at nomanssave.storage.f.a(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.G.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
[WARNING] cannot read file metadata: savedata02.hg
[WARNING] java.io.IOException: Invalid header
	at nomanssave.storage.w.<init>(Unknown Source)
	at nomanssave.storage.s.<init>(Unknown Source)
	at nomanssave.storage.p.<init>(Unknown Source)
	at nomanssave.storage.f.a(Unknown Source)
	at nomanssave.storage.f.a(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.G.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
[WARNING] cannot read file metadata: savedata03.hg
[WARNING] java.io.IOException: Invalid header
	at nomanssave.storage.w.<init>(Unknown Source)
	at nomanssave.storage.s.<init>(Unknown Source)
	at nomanssave.storage.p.<init>(Unknown Source)
	at nomanssave.storage.f.a(Unknown Source)
	at nomanssave.storage.f.a(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.G.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
[DEBUG] Storage: PS4 - Save Wizard
[DEBUG] Save Path: C:\Users\fennectech\Desktop\=EDIT=
[INFO] Reading account data...
[DEBUG] Mem Usage: 255/3762 MB
`
and here is a copy of a 4.0.3 save file from nintendo swtich 
https://transfer.sh/AMKRAE/savedata.zip

**Comment by Muzika** [comment]
Hey! If you're still interested... You can workaround the issue by copying mf_save.hg from your PC NMS and rename the save you want to edit to "save.hg"

Once you do you should be able to edit the save data from switch and import it back to the device. 


*Just make sure to rename save.hg back to its original filename when you decide to restore your modified save.

**Comment by fennectech** [comment]
I dont have a pc version

**Comment by fennectech** [comment]
I found a save on the internet and now am hapily having extra fun on switch!!!  so it looks like its going to be even easier to bring switch support to the editor as its just a matter of supporting the headers

**Comment by jimmgc** [comment]
> I found a save on the internet and now am hapily having extra fun on switch!!! so it looks like its going to be even easier to bring switch support to the editor as its just a matter of supporting the headers

Where did you found the save? Having a hard time playing the switch version.

**Comment by fennectech** [comment]
You need to download a pc save and replace 1 of the larger files with the large file from your game.  you can then load it in the save editor   ignore all account related stuff

**Comment by jimmgc** [comment]
Ok. What's the best way to get the save data from the Switch? Sorry but new to Nintendo Switch. I have the game on PC but wanted to give a try on Switch. Thanks again.

**Comment by fennectech** [comment]
you need a hacked switch for that Sent from my iPadOn Mar 6, 2023, at 5:22 PM, Muzika ***@***.***> wrote:﻿

Ok. What's the best way to get the save data from the Switch? Sorry but new to Nintendo Switch. I have the game on PC but wanted to give a try on Switch. Thanks again.

Just use the other NMS Save Editor callrd NomNom for now. It already supports Nintendo Switch.

**Comment by Muzika** [comment]
> you need a hacked switch for that Sent from my iPadOn Mar 6, 2023, at 5:22 PM, Muzika ***@***.***> wrote:﻿ Ok. What's the best way to get the save data from the Switch? Sorry but new to Nintendo Switch. I have the game on PC but wanted to give a try on Switch. Thanks again. Just use the other NMS Save Editor callrd NomNom for now. It already supports Nintendo Switch. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

That's true. But so is using this editor also. You have no other options unless it is hacked.

**Comment by fennectech** [comment]
without a hacked console you cant pull your save off the switch and you cant put it back Sent from my iPadOn Mar 6, 2023, at 10:44 PM, Muzika ***@***.***> wrote:﻿

you need a hacked switch for that Sent from my iPadOn Mar 6, 2023, at 5:22 PM, Muzika @.> wrote:﻿ Ok. What's the best way to get the save data from the Switch? Sorry but new to Nintendo Switch. I have the game on PC but wanted to give a try on Switch. Thanks again. Just use the other NMS Save Editor callrd NomNom for now. It already supports Nintendo Switch. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>

That's true. But so is using this editor also. You have no other options unless it is hacked.

**Comment by jimmgc** [comment]
Mmm. Thanks all for the feedback. Guess will give a try.

**Comment by fennectech** [comment]
@goatfungus   See this issue for all the info I’ve collected about the switch saves.     They are very similar (if not identical) in format to the PC version of the game.  However file naming convention and metadata / headers are different requiring the user to do a bit of trickery to get the save loaded in the editor and in the game.      I’ve uploaded some save data https://github.com/goatfungus/NMSSaveEditor/files/11941520/nms.zip here.  This is the latest version of the game
