### ISSUE TITLE
Account Tab greyed out

### ISSUE THREAD

**Issue by pumkinhead456** [goatfungus/NMSSaveEditor#722]
So I loaded my save only to find out that my account tab is greyed out, don't know what could cause this as I just updated the game. Here is my log
[NMSSaveEditor.log](https://github.com/goatfungus/NMSSaveEditor/files/10830320/NMSSaveEditor.log)

**Comment by 600Color** [comment]
i have the same Issue with the pc gamepass version!  im using the latest Version of Java 8 Update 361 (x64 Build 1.8.0_361-b09)

[INFO] Reading account data...
[WARNING] Error reading account data
[WARNING] java.io.EOFException: Unexpected end of offset
	at nomanssave.util.o.dE(Unknown Source)
	at nomanssave.util.o.read(Unknown Source)
	at nomanssave.util.o.read(Unknown Source)
	at nomanssave.storage.K.readBytes(Unknown Source)
	at nomanssave.storage.H.Q(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.G.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by gasova** [comment]
same here
