### ISSUE TITLE
My save doesn't show up to select

### ISSUE THREAD

**Issue by Tornadobim** [goatfungus/NMSSaveEditor#728]
Does anyone know what can it be? It just doesn't show the saves

![Screenshot_1](https://user-images.githubusercontent.com/23440278/221437891-cfea2b40-25ab-4367-b5cc-aa596e377dc2.png)

**Comment by Devilin-Pixy** [comment]
Does the command prompt or log file show anything that may be useful?
For Steam users it looks to be a correct path.

**Comment by Tornadobim** [comment]
> O prompt de comando ou o arquivo de log mostra algo que pode ser útil? Para os usuários do Steam, parece ser um caminho correto.

Log;

[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_361
[DEBUG] Working Dir: C:\Users\Tornado\Downloads\T\NMS
[INFO] Starting Editor...
[WARNING] Unable to register storage
[WARNING] java.nio.file.NoSuchFileException: C:\Users\torna\AppData\Roaming\HelloGames\NMS\st_76561198030239380
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.asIOException(Unknown Source)
	at sun.nio.fs.WindowsWatchService$Poller.implRegister(Unknown Source)
	at sun.nio.fs.AbstractPoller.processRequests(Unknown Source)
	at sun.nio.fs.WindowsWatchService$Poller.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[DEBUG] Storage: Steam
[DEBUG] Save Path: C:\Users\torna\AppData\Roaming\HelloGames\NMS\st_76561198030239380
[INFO] Reading account data...
[DEBUG] Mem Usage: 257/3805 MB
[DEBUG] Latest version: "1.11.5"
[DEBUG] Current version: "1.11.5"

**Comment by Devilin-Pixy** [comment]
Could you post a screenshot of the file contents in the save location?
It looks like it only finds 'storage' file(s), and not actually any recent save files?
'storage' files can still be present, but are no longer used since Atlas Rises update.
Are you trying to load old save files? Have you tried updating your saves in-game first?

If you are having recently created save files, I am not sure what the issue could be, but seeing the files could provide a clue

**Comment by Tornadobim** [comment]
> Could you post a screenshot of the file contents in the save location? It looks like it only finds 'storage' file(s), and not actually any recent save files? 'storage' files can still be present, but are no longer used since Atlas Rises update. Are you trying to load old save files? Have you tried updating your saves in-game first?
> 
> If you are having recently created save files, I am not sure what the issue could be, but seeing the files could provide a clue

Done!

![123](https://user-images.githubusercontent.com/23440278/221442462-5e522f16-6547-4871-ade9-5ba3a56e7cee.jpg)

**Comment by Devilin-Pixy** [comment]
The save files look to be ok. When you 'Select the File/Path' and open the Steam folder itself to show the actual save files, and only then select to 'Open' it for use with the Save Editor, it should allow you to select slots from the drop-down after. 

Go here and click 'Open'
![image](https://user-images.githubusercontent.com/7830771/221444353-e32456db-2b77-4ab3-9e6c-d963dcb4ee3a.png)

Now you should be able to select 'Game Slot'
![image](https://user-images.githubusercontent.com/7830771/221444493-cafb8b49-435d-44ef-accd-d4e0e8794b2d.png)

If the Save Editor then still does not show the saves, I am not sure what the issue could be.

**Comment by Tornadobim** [comment]
> If the Save Editor then still does not show the saves, I am not sure what the issue could be.

This is my problem :/

Not show the saves :( 

![Screenshot_1](https://user-images.githubusercontent.com/23440278/221446420-9b38b5f7-2952-4b68-979f-6e3332e2514b.png)

**Comment by Devilin-Pixy** [comment]
Could you check the reply from here: https://github.com/goatfungus/NMSSaveEditor/issues/581#issuecomment-1142626275

**Comment by Tornadobim** [comment]
@Devilin-Pixy, FULL WORK!!!!!!!!!!!!!!!!!!!!!!!!

Very thanks friend!!!!!!!!!!!!!

> Could you check the reply from here: [#581 (comment)](https://github.com/goatfungus/NMSSaveEditor/issues/581#issuecomment-1142626275)

**Comment by BluegemEmpire** [comment]
Mine wont even let me select a path, theres no save file, but I have a save.

**Comment by goatfungus** [comment]
Try again, there were issues with the file open dialogs which should now be resolved.
