### ISSUE TITLE
Unable to save changes

### ISSUE THREAD

**Issue by Exokem** [goatfungus/NMSSaveEditor#729]
When I try to use the 'save changes' function, an error appears with the following description: 'There was an error saving the file.'

It has been a few years since I last used the save editor, so I have updated it as well as my saves (in-game). My saves are recognized within the editor, but I am not able to save any changes.

![image](https://user-images.githubusercontent.com/26678865/221466078-691e5075-8e16-4397-a07e-887c30a81262.png)

The console output is not apparently very useful: 
![image](https://user-images.githubusercontent.com/26678865/221466353-dbe71607-8da2-4366-85a1-518b55de8cc7.png)
This specific output is from the following actions: 
1. Select a game slot
2. Click 'Save As'
3. Select an empty game slot
4. Click 'Replace/Save'
5. Click 'Save Changes'

I am not sure why the 'Modified' date is appearing incorrectly.

**Comment by GrumpyKoala1966** [comment]
I've found that if there is an open tab relating to the game or the game it's self is still running in back ground, saving can't be done

**Comment by Exokem** [comment]
> I've found that if there is an open tab relating to the game or the game it's self is still running in back ground, saving can't be done

Do you mean a file explorer window as a tab? I am sure at least that the game is closed when I tried to save the file.
Even if I close all explorer tabs, the issue persists.

**Comment by GrumpyKoala1966** [comment]
H'mmm not sure then, try rebooting computer maybe that will help, other than that I'm clueless..

**Comment by Devilin-Pixy** [comment]
Did you create the save first, so Steam actually accepts it to begin with? With Steam Cloud Sync, the save slot is required to be generated at least once before being able to save to it. I suggest to start a new save in-game, make sure it saved, to then overwrite it in the editor.

**Comment by goatfungus** [comment]
The save editor does attempt to create the mf_saveX.hg files, but if the storage device doesn't allow the file to be saved then you'll see this kind of error. Maybe the log shows a bit more details?

**Comment by Exokem** [comment]
> The save editor does attempt to create the mf_saveX.hg files, but if the storage device doesn't allow the file to be saved then you'll see this kind of error. Maybe the log shows a bit more details?

I ended up starting a new save, but these are some of the logs I was able to find: 
```
[ERROR] Could not write save file: save.hg
[ERROR] java.io.FileNotFoundException: C:\Users\user\AppData\Roaming\HelloGames\NMS\st_76561198141375977\mf_save.hg (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at nomanssave.storage.E.a(Unknown Source)
	at nomanssave.storage.A.b(Unknown Source)
	at nomanssave.Application.v(Unknown Source)
	at nomanssave.Application.b(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
```
[WARNING] Cannot load backup.1677512584476.zip
[WARNING] java.io.IOException: Invalid backup file
	at nomanssave.storage.z.<init>(Unknown Source)
	at nomanssave.storage.C.accept(Unknown Source)
	at java.base/java.io.File.listFiles(File.java:1353)
	at nomanssave.storage.B.bv(Unknown Source)
	at nomanssave.Application.e(Unknown Source)
	at nomanssave.Application.a(Unknown Source)
	at nomanssave.I.setSelectedItem(Unknown Source)
	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:609)
	at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:654)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:946)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:551)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by tarasis** [comment]
I just ran into this, and I don't remember having to create an additional save in the game to have the editor save a backup of my main save to it (just in case something goes wrong with the edit)
