### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by Thejameshenry** [goatfungus/NMSSaveEditor#735]
It's probably related to yesterdays game update, but if not wanted to post here.

```
Reading save file...
  Slot: Slot 1 - CUSTOM - Mar 4, 17:09
  Filename: save2.hg
  using name mappings: NMS 4.1 (savegame)
  WARNING: name mapping not found: ?n7
  WARNING: name mapping not found: heA
  WARNING: name mapping not found: tj1
  WARNING: name mapping not found: yqB
  WARNING: name mapping not found: Qb3
Finished.
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: No enum constant nomanssave.structures.h.MiniRobo
        at java.lang.Enum.valueOf(Unknown Source)
        at nomanssave.structures.h.valueOf(Unknown Source)
        at nomanssave.structures.g.cc(Unknown Source)
        at nomanssave.ao.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
        at nomanssave.an.a(Unknown Source)
        at nomanssave.Application.s(Unknown Source)
        at nomanssave.Application.e(Unknown Source)
        at nomanssave.Application.a(Unknown Source)
        at nomanssave.I.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedItem(Unknown Source)
        at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

love your editor 👍

**Comment by Bamajs3080** [comment]
Did you get this fixed because I believe I'm have the same problem after I got an update on 3/15 at like 11:30pm

**Comment by Thejameshenry** [comment]
Nope, still unable to use editor :(

**Comment by goatfungus** [comment]
This issue should be resolved now, I have added the missing types to the editor.
