### ISSUE TITLE
Can't save changes

### ISSUE THREAD

**Issue by Geokrit** [goatfungus/NMSSaveEditor#755]
After attempting to save my file, it fails. I think it has something to do with either the massive block of "[WARNING] name mapping not found" or this error message in the log: 

[ERROR] java.io.FileNotFoundException: C:\Program Files (x86)\No Man's Sky Save Editor\4 Interceptor SE\backups\backup7.1681005845404.zip (Access is denied)

Here is the rest of the log just in case I'm wrong:

[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_361
[DEBUG] Working Dir: C:\Program Files (x86)\No Man's Sky Save Editor\4 Interceptor SE
[INFO] Starting Editor...
[INFO] Reading metadata for accountdata.hg
[DEBUG] Extra: 280
[INFO] Reading metadata for save.hg
[DEBUG] DecompressedSize: 2803470
[DEBUG] Unknown1: 4142
[INFO] Version: 1
[INFO] TotalPlayTime: 48:03
[DEBUG] Extra: 280
[INFO] Reading metadata for save2.hg
[DEBUG] DecompressedSize: 2892380
[DEBUG] Unknown1: 4142
[INFO] Version: 1
[INFO] TotalPlayTime: 48:03
[DEBUG] Extra: 280
[INFO] Reading metadata for save3.hg
[DEBUG] DecompressedSize: 3860586
[DEBUG] Unknown1: 4142
[INFO] Version: 1
[INFO] TotalPlayTime: 65:23
[DEBUG] Extra: 280
[INFO] Reading metadata for save4.hg
[DEBUG] DecompressedSize: 3860587
[DEBUG] Unknown1: 4142
[INFO] Version: 1
[INFO] TotalPlayTime: 65:23
[DEBUG] Extra: 280
[INFO] Reading metadata for save5.hg
[DEBUG] DecompressedSize: 1662799
[DEBUG] Unknown1: 4142
[INFO] Version: 1
[INFO] TotalPlayTime: 2:23
[DEBUG] Extra: 280
[INFO] Reading metadata for save6.hg
[DEBUG] DecompressedSize: 1661906
[DEBUG] Unknown1: 4142
[INFO] Version: 1
[INFO] TotalPlayTime: 2:21
[DEBUG] Extra: 280
[INFO] Reading metadata for save7.hg
[DEBUG] DecompressedSize: 2789880
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 14:32
[DEBUG] Extra: 280
[INFO] Reading metadata for save8.hg
[DEBUG] DecompressedSize: 2789862
[DEBUG] Unknown1: 4144
[INFO] Version: 1
[INFO] TotalPlayTime: 14:32
[DEBUG] Extra: 280
[DEBUG] Storage: Steam
[DEBUG] Save Path: C:\Users\User\AppData\Roaming\HelloGames\NMS\st_76561198286993499
[INFO] Reading account data...
[INFO] using name mappings: NMS 4.2 (account)
[WARNING] invalid switch detected: 12
[DEBUG] Mem Usage: 129/1894 MB
[DEBUG] Latest version: "1.12.0"
[DEBUG] Current version: "1.12.0"
[INFO] Loading saves for Slot 4...
[INFO] Reading save file...
[INFO] Slot: Slot 4 - NORMAL - Apr 8, 18:13
[INFO] Filename: save7.hg
[INFO] using name mappings: NMS 4.2 (savegame)
[WARNING] name mapping not found: yID
[WARNING] name mapping not found: X;?
[WARNING] name mapping not found: WmI
[WARNING] name mapping not found: IsL
[WARNING] name mapping not found: MMA
[WARNING] name mapping not found: me6
[WARNING] name mapping not found: 4q6
[WARNING] name mapping not found: AeI
[WARNING] name mapping not found: L8=
[WARNING] name mapping not found: rER
[WARNING] name mapping not found: OHU
[WARNING] name mapping not found: 4=k
[WARNING] name mapping not found: BBw
[WARNING] name mapping not found: SCS
[WARNING] name mapping not found: i7<
[WARNING] name mapping not found: gWW
[WARNING] name mapping not found: 4Yf
[WARNING] name mapping not found: y=c
[WARNING] name mapping not found: uK<
[WARNING] name mapping not found: J>I
[WARNING] name mapping not found: Gc7
[WARNING] name mapping not found: cQc
[WARNING] name mapping not found: 7dP
[WARNING] name mapping not found: 67b
[WARNING] name mapping not found: 02l
[WARNING] name mapping not found: qbd
[WARNING] name mapping not found: 8L;
[WARNING] name mapping not found: 3ol
[WARNING] name mapping not found: WAV
[WARNING] name mapping not found: YIB
[WARNING] name mapping not found: LFj
[WARNING] name mapping not found: hQ1
[WARNING] name mapping not found: UtG
[WARNING] name mapping not found: 9J<
[WARNING] name mapping not found: huR
[WARNING] name mapping not found: N=w
[WARNING] name mapping not found: txU
[WARNING] name mapping not found: Kex
[WARNING] name mapping not found: B29
[WARNING] name mapping not found: Ubj
[WARNING] name mapping not found: nW;
[WARNING] name mapping not found: mRF
[WARNING] name mapping not found: 7pJ
[WARNING] name mapping not found: CX9
[WARNING] name mapping not found: 753
[WARNING] name mapping not found: GFy
[WARNING] name mapping not found: s;F
[WARNING] name mapping not found: gsT
[WARNING] name mapping not found: aS@
[WARNING] name mapping not found: TuK
[WARNING] name mapping not found: xFq
[WARNING] name mapping not found: uEG
[WARNING] name mapping not found: vnq
[WARNING] name mapping not found: >TS
[WARNING] name mapping not found: 2mY
[WARNING] name mapping not found: Z@U
[WARNING] name mapping not found: QqY
[WARNING] name mapping not found: BQo
[WARNING] name mapping not found: ByQ
[WARNING] name mapping not found: 5;w
[WARNING] name mapping not found: 33q
[WARNING] name mapping not found: S2k
[WARNING] name mapping not found: @xZ
[WARNING] name mapping not found: WoW
[WARNING] name mapping not found: eem
[WARNING] name mapping not found: MLJ
[WARNING] name mapping not found: l?S
[WARNING] name mapping not found: TbT
[WARNING] name mapping not found: Zq4
[WARNING] name mapping not found: TlS
[WARNING] name mapping not found: W=G
[WARNING] name mapping not found: @xT
[WARNING] name mapping not found: c=A
[WARNING] name mapping not found: iBF
[WARNING] name mapping not found: kOX
[WARNING] name mapping not found: H:b
[WARNING] name mapping not found: KxX
[WARNING] name mapping not found: 6:a
[WARNING] name mapping not found: TOS
[WARNING] name mapping not found: wFw
[WARNING] name mapping not found: Ch:
[WARNING] name mapping not found: VUh
[WARNING] name mapping not found: H9K
[WARNING] name mapping not found: ec8
[WARNING] name mapping not found: rHh
[WARNING] name mapping not found: e;b
[WARNING] name mapping not found: E?H
[WARNING] name mapping not found: LMQ
[WARNING] name mapping not found: RxV
[WARNING] name mapping not found: YeP
[WARNING] name mapping not found: uWE
[WARNING] name mapping not found: ?n7
[WARNING] name mapping not found: heA
[WARNING] name mapping not found: tj1
[WARNING] name mapping not found: yqB
[WARNING] name mapping not found: Qb3
[INFO] Finished.
[INFO] Formatting JSON...
[ERROR] Could not write save file: save7.hg
[ERROR] java.io.FileNotFoundException: C:\Program Files (x86)\No Man's Sky Save Editor\4 Interceptor SE\backups\backup7.1681005845404.zip (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at nomanssave.storage.E.a(Unknown Source)
	at nomanssave.storage.A.b(Unknown Source)
	at nomanssave.Application.p(Unknown Source)
	at nomanssave.Application.f(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by goatfungus** [comment]
Firstly, ignore the "Name mapping not found" warnings. They are ONLY warnings and have no affect on the editor.

It looks like your issue is that the editor cannot write to the file. Either you are running the editor under reduced permissions, or you already have the zip file open. Sometimes Windows will lock areas of your Program Files directory so they aren't tampered with, so I would start there.

**Comment by Geokrit** [comment]
Alright, so I've updated the permissions and the issue is fixed! I originally thought that I already updated the permissions, as I had only done that with the .bat and .jar files, but then I updated them on the actual save editor file, and that fixed it! Thanks!
