### ISSUE TITLE
cannot read file 

### ISSUE THREAD

**Issue by Cowpooke** [goatfungus/NMSSaveEditor#867]
[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 19.0.1
[DEBUG] Java Architecture: amd64
[DEBUG] Operating System: Windows 11
[DEBUG] Working Dir: B:\a\gfungus
[DEBUG] Look and Feel: FlatLaf macOS Dark
[INFO] Starting Editor...
[INFO] Reading Container Index
[DEBUG] header: 14
[DEBUG] count: 2
[DEBUG] name: HelloGames.NoMansSky_bs190hzg1sesy!NoMansSky
[DEBUG] unknown2: -598124608
[DEBUG] unknown3: 31051265
[DEBUG] unknown4: 2
[DEBUG] appid: f6ee4b6e-fcb3-4770-ae10-1e5008953aa6
[DEBUG] unknown5: 268435456
[INFO] Slot1Auto
[DEBUG] filename: Slot1Auto
[DEBUG] id: "0x8DB9C16CF39C144"
[DEBUG] suffix: 13
[DEBUG] unknown1: 2
[DEBUG] containerPath: 1A6BD775167949CBB5121CD55E44C4A1
[DEBUG] timestamp: Sun Aug 13 23:18:57 ICT 2023
[DEBUG] totalSize: 27336
[INFO] Slot1Manual
[DEBUG] filename: Slot1Manual
[DEBUG] id: "0x8DB9C16CF2E5C5F"
[DEBUG] suffix: 8
[DEBUG] unknown1: 2
[DEBUG] containerPath: B8853CE8339B4141B35A90D33A8BB4C2
[DEBUG] timestamp: Sun Aug 13 23:12:07 ICT 2023
[DEBUG] totalSize: 27275
[INFO] Slot1Auto
[DEBUG] header: 4
[DEBUG] name: data
[DEBUG] filename: 4CE91DA255454CCFB7870A727149FB86
[DEBUG] filename2: A40B36A2F5A046528BC93EE9DA379CB2
[DEBUG] name: meta
[DEBUG] filename: E21D6F109DE943E982F9B07203E37496
[DEBUG] filename2: E7A1130D919644249A110AFFEBCDF8E4
[WARNING] Cannot read file data
[WARNING] java.io.IOException: data size mismatch
	at nomanssave.fV.<init>(Unknown Source)
	at nomanssave.fW.<init>(Unknown Source)
	at nomanssave.fR.<init>(Unknown Source)
	at nomanssave.fq.a(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.w.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[INFO] Slot1Manual
[DEBUG] header: 4
[DEBUG] name: data
[DEBUG] filename: F11E93F8A0D049538309524F094F8B16
[DEBUG] filename2: 476954F8A4374FDDB6B8E5027C366D53
[DEBUG] name: meta
[DEBUG] filename: 892F7386E82148939ABD71DAE6491596
[DEBUG] filename2: 3E721A8FB7DA4550902A5BF5B1601986
[WARNING] Cannot read file data
[WARNING] java.io.IOException: data size mismatch
	at nomanssave.fV.<init>(Unknown Source)
	at nomanssave.fW.<init>(Unknown Source)
	at nomanssave.fR.<init>(Unknown Source)
	at nomanssave.fq.a(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.w.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[DEBUG] Storage: Xbox Game Pass
[DEBUG] Save Path: C:\Users\Administrator\AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs\000901F591BE43F3_29070100B936489ABCE8B9AF3980429C
[INFO] Reading account data...
[DEBUG] Mem Usage: 132/2112 MB
[DEBUG] Latest version: "1.14.2"
[DEBUG] Current version: "1.14.2"

**Comment by captain-soban** [comment]
getting the same error. I was able to edit saves for a while then this happened
