### ISSUE TITLE
Discovery tab - Known Words "Learn All" not working

### ISSUE THREAD

**Issue by Mike-Blackwell** [goatfungus/NMSSaveEditor#874]
Title sez it all

**Comment by areithropos** [comment]
True. Changing stuff with the words slows the editor down for me.

**Comment by Spl1x6** [comment]
Same thing happening to me

**Comment by bookerthegeek** [comment]
Heyo.

The learn all button did not work.

Manually clicking a bunch of check box also did not teach me those words, although I got an achievement in game for learning "X amount of words."

Version Latest as of 6/27/2023 

The log file shows the following after selecting the learn all button:

```
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException
[STDERR] 	at nomanssave.eV.set(Unknown Source)
[STDERR] 	at nomanssave.eV.a(Unknown Source)
[STDERR] 	at nomanssave.gx.a(Unknown Source)
[STDERR] 	at nomanssave.gx.a(Unknown Source)
[STDERR] 	at nomanssave.gy.a(Unknown Source)
[STDERR] 	at nomanssave.ay.actionPerformed(Unknown Source)
[STDERR] 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
[STDERR] 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
[STDERR] 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
[STDERR] 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[STDERR] 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
[STDERR] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
[STDERR] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
[STDERR] 	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
[STDERR] 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
[STDERR] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
[STDERR] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
[STDERR] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
[STDERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
[STDERR] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
[STDERR] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
[STDERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by goatfungus** [comment]
This should be working now as of the 1.14.4 version.

**Comment by Mike-Blackwell** [comment]
Many thanxs for the service, seems to work!
