### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by yinz0327** [goatfungus/NMSSaveEditor#894]
There will be an error when I run it

[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 20.0.2
[DEBUG] Java Architecture: amd64
[DEBUG] Operating System: Windows 11
[DEBUG] Working Dir: F:\BaiduNetdiskDownload\NMSSaveEditor (1)
[DEBUG] Look and Feel: FlatLaf IntelliJ
[INFO] Starting Editor...
[DEBUG] Mem Usage: 1074/17163 MB
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
[STDERR] 	at java.base/java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870)
[STDERR] 	at java.base/java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487)
[STDERR] 	at java.base/java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:426)
[STDERR] 	at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:222)
[STDERR] 	at java.base/java.util.Arrays.sort(Arrays.java:1041)
[STDERR] 	at java.desktop/sun.awt.shell.Win32ShellFolderManager2.get(Win32ShellFolderManager2.java:319)
[STDERR] 	at java.desktop/sun.awt.shell.ShellFolder.get(ShellFolder.java:272)
[STDERR] 	at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI$DirectoryComboBoxModel.addItem(MetalFileChooserUI.java:1031)
[STDERR] 	at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI.doDirectoryChanged(MetalFileChooserUI.java:719)
[STDERR] 	at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI$5.propertyChange(MetalFileChooserUI.java:808)
[STDERR] 	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
[STDERR] 	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
[STDERR] 	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
[STDERR] 	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8716)
[STDERR] 	at java.desktop/javax.swing.JFileChooser.setCurrentDirectory(JFileChooser.java:610)
[STDERR] 	at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:364)
[STDERR] 	at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:310)
[STDERR] 	at nomanssave.ej.<init>(Unknown Source)
[STDERR] 	at nomanssave.ej.b(Unknown Source)
[STDERR] 	at nomanssave.Application.k(Unknown Source)
[STDERR] 	at nomanssave.Application.p(Unknown Source)
[STDERR] 	at nomanssave.v.run(Unknown Source)
[STDERR] 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
[STDERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
[STDERR] 	at java.base/java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870)
[STDERR] 	at java.base/java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487)
[STDERR] 	at java.base/java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:426)
[STDERR] 	at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:222)
[STDERR] 	at java.base/java.util.Arrays.sort(Arrays.java:1041)
[STDERR] 	at java.desktop/sun.awt.shell.Win32ShellFolderManager2.get(Win32ShellFolderManager2.java:319)
[STDERR] 	at java.desktop/sun.awt.shell.ShellFolder.get(ShellFolder.java:272)
[STDERR] 	at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI$DirectoryComboBoxModel.addItem(MetalFileChooserUI.java:1031)
[STDERR] 	at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI.doDirectoryChanged(MetalFileChooserUI.java:719)
[STDERR] 	at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI$5.propertyChange(MetalFileChooserUI.java:808)
[STDERR] 	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
[STDERR] 	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
[STDERR] 	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
[STDERR] 	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8716)
[STDERR] 	at java.desktop/javax.swing.JFileChooser.setCurrentDirectory(JFileChooser.java:610)
[STDERR] 	at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:364)
[STDERR] 	at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:310)
[STDERR] 	at nomanssave.ej.<init>(Unknown Source)
[STDERR] 	at nomanssave.ej.b(Unknown Source)
[STDERR] 	at nomanssave.Application.k(Unknown Source)
[STDERR] 	at nomanssave.Application.d(Unknown Source)
[STDERR] 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
[STDERR] 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
[STDERR] 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
[STDERR] 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[STDERR] 	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
[STDERR] 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029)
[STDERR] 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073)
[STDERR] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
[STDERR] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
[STDERR] 	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
[STDERR] 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
[STDERR] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
[STDERR] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
[STDERR] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
[STDERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
[STDERR] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
[STDERR] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[STDERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[STDERR] Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
[STDERR] 	at java.base/java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870)
[STDERR] 	at java.base/java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487)
[STDERR] 	at java.base/java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:426)
[STDERR] 	at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:222)
[STDERR] 	at java.base/java.util.Arrays.sort(Arrays.java:1041)
[STDERR] 	at java.desktop/sun.awt.shell.Win32ShellFolderManager2.get(Win32ShellFolderManager2.java:319)
[STDERR] 	at java.desktop/sun.awt.shell.ShellFolder.get(ShellFolder.java:272)
[STDERR] 	at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI$DirectoryComboBoxModel.addItem(MetalFileChooserUI.java:1031)
[STDERR] 	at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI.doDirectoryChanged(MetalFileChooserUI.java:719)
[STDERR] 	at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI$5.propertyChange(MetalFileChooserUI.java:808)
[STDERR] 	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
[STDERR] 	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
[STDERR] 	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
[STDERR] 	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8716)
[STDERR] 	at java.desktop/javax.swing.JFileChooser.setCurrentDirectory(JFileChooser.java:610)
[STDERR] 	at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:364)
[STDERR] 	at java.desktop/javax.swing.JFileChooser.<init>(JFileChooser.java:310)
[STDERR] 	at nomanssave.ej.<init>(Unknown Source)
[STDERR] 	at nomanssave.ej.b(Unknown Source)
[STDERR] 	at nomanssave.Application.k(Unknown Source)
[STDERR] 	at nomanssave.Application.d(Unknown Source)
[STDERR] 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
[STDERR] 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
[STDERR] 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
[STDERR] 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[STDERR] 	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
[STDERR] 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029)
[STDERR] 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073)
[STDERR] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
[STDERR] 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
[STDERR] 	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
[STDERR] 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
[STDERR] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
[STDERR] 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
[STDERR] 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
[STDERR] 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
[STDERR] 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
[STDERR] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
[STDERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
[STDERR] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
[STDERR] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[STDERR] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
[STDERR] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
[STDERR] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[STDERR] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by MGJerry** [comment]
I'm not that proficient in debugging, but line 9 is leading me to believe there's some incompatibility between specific Java and Windows version. Maybe try downloading the [recommended Java version](https://www.java.com/download/ie_manual.jsp) (aka Java 8) and see if you still run into the same issue.
