### ISSUE TITLE
There was an error loading the file

### ISSUE THREAD

**Issue by nymrodeth** [goatfungus/NMSSaveEditor#955]
It says "Slot 1 - [EMPTY]" and popping an error like that. I was using the editor 2-3 hours ago. Now its not working.
![Screenshot_5](https://github.com/goatfungus/NMSSaveEditor/assets/162159832/07da4d9c-026f-4eac-954b-b8e87f64bacb)

**Comment by Harurunya** [comment]
same.
ms store(gamepass) version updated today.
so it seems editor can't load newest saves.
waiting for updates

**Comment by githubUser01946** [comment]
Dropped by to say "same".

**Comment by iSolars** [comment]
Exactly the same error. Hope they fix it soon

**Comment by eropel** [comment]
Same but with error attached.

[WARNING] Cannot read file data
[WARNING] java.io.IOException: data size mismatch
	at nomanssave.fV.<init>(Unknown Source)
	at nomanssave.fW.<init>(Unknown Source)
	at nomanssave.fR.<init>(Unknown Source)
	at nomanssave.fq.a(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.w.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by iSolars** [comment]
Initializing environment...
Starting Editor...
Reading Container Index
  AccountData
  Settings
  Slot1Auto
  Slot1Manual
AccountData
Slot1Auto
  version: 1
  totalPlayTime: 22:27
WARNING: Could not read game mode from Slot1Auto
Slot1Manual
  version: 1
  totalPlayTime: 22:27
WARNING: Could not read game mode from Slot1Manual
Reading account data...
Loading saves for Slot 1...
Reading save file...
  Slot: Slot 1 - [EMPTY]
  Filename: Slot1Manual
ERROR: Could not load save file: Slot1Manual

**Comment by githubUser01946** [comment]
There's been a change with how NMS saves games on GamesPass apparentlyand that is why we are getting this. We just need to wait for @goatfungus to figure it out and update.

**Comment by Soleil7025** [comment]
Well, I found this tool for the first time yesterday, and the result is the same problem. I once suspected that it was a program error in my computer … I hope this problem will not be too complicated. I can't wait to use this tool. I am not satisfied with the appearance of my spaceship! I need it. I'm going crazy. My obsessive-compulsive disorder reappears.＞＜#

**Comment by StevnJessie1** [comment]
If I bypass the BAT and run the jar by itself, I get this in the log. Also using the BAT file. Welp, I used up what little I know about Java.
[WARNING] Could not read game mode from Slot1Auto
[WARNING] java.io.EOFException: Buffer too small

**Comment by goatfungus** [comment]
Can you please email me a copy of your save files?
If you could zip them all up with WinZip or something equivalent I will have a look and see what the issue is. I don't have the Xbox version of NMS so I have to rely on users to send me the save data.

**Comment by githubUser01946** [comment]
> Can you please email me a copy of your save files? If you could zip them all up with WinZip or something equivalent I will have a look and see what the issue is. I don't have the Xbox version of NMS so I have to rely on users to send me the save data.

I can try. I assumeI just copy the folder that's in the Hello Games one and your email address is somewhere around here.

Also Xbox doesn't have the new update yet so it's still "Omega", for now.

**Comment by GhostER01** [comment]
Greetings! I encountered the same problem, did you manage to solve it?
