### ISSUE TITLE
Could not load save file: Slot3Manual [ERROR] java.io.EOFException: Buffer too small

### ISSUE THREAD

**Issue by dhall8802** [goatfungus/NMSSaveEditor#966]
Hey @goatfungus,
Looking at your save editor and it looks awesome. I have a save I started from the Omega expedition on Xbox One and occasionally play on PC via Gamepass. When trying to open my save, I get an error that states "There was an error loading the file." and that's it. I checked the NMSSaveEditor.log and I found the error message:

[INFO] Loading saves for Slot 3...
[INFO] Reading save file...
[INFO] Slot: Slot 3 - [EMPTY]
[INFO] Filename: Slot3Manual
[ERROR] Could not load save file: Slot3Manual
[ERROR] java.io.EOFException: Buffer too small
	at nomanssave.gX.dZ(Unknown Source)
	at nomanssave.gX.read(Unknown Source)
	at nomanssave.ff.bJ(Unknown Source)
	at nomanssave.ff.a(Unknown Source)
	at nomanssave.fV.a(Unknown Source)
	at nomanssave.fW.M(Unknown Source)
	at nomanssave.Application.l(Unknown Source)
	at nomanssave.Application.e(Unknown Source)
	at nomanssave.Application.a(Unknown Source)
	at nomanssave.D.setSelectedItem(Unknown Source)
	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
	Suppressed: nomanssave.eX: Missing null terminator
		at nomanssave.ff.close(Unknown Source)
		... 42 more
[DEBUG] Storage: Xbox Game Pass

Any idea why my buffer might be too low to open my save file? Anything I can do on my end to increase the buffer? No rush on this, you are awesome for taking the time to put this all together and work on this in your spare time!

**Comment by goatfungus** [comment]
Can you please email me a copy of your save files?
If you could zip them all up with WinZip or something equivalent I will have a look and see what the issue is. I don't have the Xbox version of NMS so I have to rely on users to send me the save data.

**Comment by goatfungus** [comment]
I have been working on the editor all day and have released a new version with updated WGS/XBox support. Hope it works out for you :)
