### ISSUE TITLE
Cannot update editor; Acccess Denied

### ISSUE THREAD

**Issue by LordOfTheEagles** [goatfungus/NMSSaveEditor#990]
I get this message when I start the .bat:

Initializing environment...
Starting Editor...
Starting download...
Restarting editor...
Access is denied.
        0 file(s) moved.
Initializing environment...
Starting Editor...
Starting download...
Restarting editor...
Access is denied.
        0 file(s) moved.
Initializing environment...
Starting Editor...

Am I doing something wrong?

**Comment by LordOfTheEagles** [comment]
It also says:

Reading metadata for accountdata.hg
WARNING: cannot read file metadata: mf_accountdata.hg
Reading metadata for save3.hg
WARNING: cannot read file metadata: mf_save3.hg
Reading metadata for save4.hg
WARNING: cannot read file metadata: mf_save4.hg

I also tried disabling my Antivirus, and I still get the original "Access denied".

**Comment by LordOfTheEagles** [comment]
Error: Unable to access jarfile NMSSaveEditor.jar when run as admin
Here's the log too if you need it.

[DEBUG] Java Vendor: Oracle Corporation
[DEBUG] Java Version: 1.8.0_411
[DEBUG] Working Dir: C:\NMS\NMSSE
[INFO] Starting Editor...
[INFO] Reading metadata for accountdata.hg
[WARNING] cannot read file metadata: mf_accountdata.hg
[WARNING] java.io.IOException: Invalid metadata header: 7ab66bfe
	at nomanssave.storage.x.a(Unknown Source)
	at nomanssave.storage.x.b(Unknown Source)
	at nomanssave.storage.E.<init>(Unknown Source)
	at nomanssave.storage.y.<init>(Unknown Source)
	at nomanssave.storage.x.<init>(Unknown Source)
	at nomanssave.storage.f.a(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.G.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
[INFO] Reading metadata for save3.hg
[WARNING] cannot read file metadata: mf_save3.hg
[WARNING] java.io.IOException: Invalid metadata header: 9cdff5a5
	at nomanssave.storage.x.a(Unknown Source)
	at nomanssave.storage.x.b(Unknown Source)
	at nomanssave.storage.E.<init>(Unknown Source)
	at nomanssave.storage.A.<init>(Unknown Source)
	at nomanssave.storage.x.<init>(Unknown Source)
	at nomanssave.storage.f.a(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.G.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
[INFO] Reading metadata for save4.hg
[WARNING] cannot read file metadata: mf_save4.hg
[WARNING] java.io.IOException: Invalid metadata header: a9d644c4
	at nomanssave.storage.x.a(Unknown Source)
	at nomanssave.storage.x.b(Unknown Source)
	at nomanssave.storage.E.<init>(Unknown Source)
	at nomanssave.storage.A.<init>(Unknown Source)
	at nomanssave.storage.x.<init>(Unknown Source)
	at nomanssave.storage.f.a(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.Application.<init>(Unknown Source)
	at nomanssave.G.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
[DEBUG] Storage: Steam
